### ISSUE TITLE
Cache question about `[UIImageView yy_setImageWithURL:placeholder:options:progress:transform:completion:]`

### ISSUE THREAD

**Issue by xilin** [ibireme/YYWebImage#1]
Thanks for the lib.

I have a question on the `[UIImageView yy_setImageWithURL:placeholder:options:progress:transform:completion:]` method.

It seems that the method will cache the original image download from network. If I defined some transform action such as adding corner radius, will the new image be cached? If not, how about the list performance?

Thanks.

**Comment by ibireme** [comment]
Image processing code is executed in the background thread, the transformed image will be cached.
                   
You can also create and use a new YYWebImageManager to cache the transformed images.

**Comment by xilin** [comment]
@ibireme I'm sorry that I didn't describe my question clearly. And after read the implementation(especially in the file `YYWebImageOperation.h`), it seems that if I defined a transform block, the image cached for the url will just be the transformed one without caching the original image.

Am i right? If so, when next time I request the url again without the block, the transformed image will be return instead of the original one? Can we have some option to control that?

**Comment by ibireme** [comment]
You can create a new manager with your custom cache for the transformed images.

See this example:
https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusHelper.m#L81-L94
https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusCell.m#L754-L760

**Comment by xilin** [comment]
@ibireme That's great. Thanks!

**Comment by xilin** [comment]
@ibireme Is there a good way to cache the original image and the transformed image at the same time?

**Comment by ibireme** [comment]
No.
I'll add some new api in the future to support it, and it might seem like this: 

    [UIImageView yy_setImageWithURL:placeholder:options:transformKey:transform:completion:]

**Comment by xilin** [comment]
Thanks. That's would be great.

**Comment by karosLi** [comment]
so when the new api with transformKey come?
