### ISSUE TITLE
图片下载失败相关问题

### ISSUE THREAD

**Issue by deqth** [ibireme/YYWebImage#10]
我想请问下  如果图片下载失败后默认的是继续重新下载吗还是需要其他的选项设置

**Comment by ibireme** [comment]
失败后会在回调里传入 error 信息。如果下次再尝试下载，仍然会尝试重新下载。

考虑到有时可能只是网络问题、CDN尚未同步完成等临时错误，这里并不会阻止失败后的重复下载。如果你需要这个功能，可以在获得 error 信息后自己判断。

**Comment by deqth** [comment]
明白了  谢谢

**Comment by Sky891028** [comment]
看到YYWebImageOptions里面没有retry的参数 希望可以添加一个这样的参数

**Comment by ibireme** [comment]
添加了 `YYWebImageOptionIgnoreFailedURL` flag。
当使用这个 flag 时，下载失败的 URL 会加入黑名单并避免再次下载。

**Comment by deqth** [comment]
想请问下这个图片缓存机制  是默认存储在磁盘上的吗  如果是的话默认存储时间是多久还是需要手动去去除缓存

**Comment by ibireme** [comment]
默认是用 YYImageCache 缓存的，内部包含一个内存缓存和磁盘缓存。

缓存都可以自己控制最大容量、存活时间等，详情可以看 YYMemoryCache 和 YYDiskCache 头文件。
获取和清空缓存可以看这个问题：#3
