### ISSUE TITLE
针对 ipv6 有没有可能会发布一个兼容版本,兼容 ipv4和v6?

### ISSUE THREAD

**Issue by buoge** [ibireme/YYWebImage#101]
类似AFNetWorking这种方式
![image](https://cloud.githubusercontent.com/assets/504726/15661584/4ea6a1c6-271b-11e6-8813-6afdb07b1817.png)

**Comment by ibireme** [comment]
YYWebImage 是基于 NSURLConnection 的，这个属于上层网络接口，在 iOS9.2 上是能自动兼容 IPv6 的（硬编码 IPv4 地址也没问题）。

另外，AF 的这个宏定义其实没什么用处，这个可以看下苹果的 Reachability 的 readme 说明。
