### ISSUE TITLE
多张大尺寸图片，容易内存溢出

### ISSUE THREAD

**Issue by liuweiisme** [ibireme/YYWebImage#102]
机型：iphone4s 版本：ios 7.0.2，当我在UITableView中加载大量的大尺寸图片时（2M左右），就会导致内存溢出，请问如何解决这个问题？

**Comment by ibireme** [comment]
2M 是只 JPG 压缩后的文件体积吗？那没办法，图片解压本来就要消耗那么多内存，机型内存不够那肯定会 Memory Warning 或退出）。通常做法是服务端压缩好图片，客户端再来显示。

如果需要显示单张大图，像图片浏览器那样缩放，那推荐手动用 CATiledLayer/CGContextDrawImage 之类的方式进行 Downsizing。苹果有个简单的 Demo 可以参考下：Large Image Downsizing。

**Comment by liuweiisme** [comment]
感谢你的回答，我能否先下载图片，处理后展现到界面，这样会减少内存吗？

**Comment by ibireme** [comment]
也可以，可以在 transform 中手动进行 downsizing。

但这种方法算是治标不治本吧，用户耗费了 2M 的流量，也等待了一段时间来进行本地压缩，结果只看到了一张小图片这个很说不过去吧。。
