### ISSUE TITLE
YYWebImageOperation 里面的lock 没有初始化？

### ISSUE THREAD

**Issue by vedon** [ibireme/YYWebImage#106]
YYWebImageOperation 里面的lock 没有初始化？

**Comment by ibireme** [comment]
哦。。好低级的错误😓
感谢提出问题！

Fixed:https://github.com/ibireme/YYWebImage/commit/b7764e8bb96988a2e9ccba15af489c09d779d80f

**Comment by vedon** [comment]
我们要接入你的框架，哈哈哈

**Comment by ibireme** [comment]
😬
