### ISSUE TITLE
Get image from disk without caching it in memory

### ISSUE THREAD

**Issue by storix** [ibireme/YYWebImage#108]
I was using the following code to get the image from the disk cache:

`YYImageCache.sharedCache().getImageForKey(diskCacheKey, withType: .Disk)`

After fetching a bunch of images I discovered that the memory usage was highly increased. A bit of searching revealed it was due to [this](https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYImageCache.m#L199) line in `getImageForKey` method. 

For now to reduce the memory usage I must add the following line after each `getImageForKey` call:

`YYImageCache.sharedCache().memoryCache.removeObjectForKey(diskCacheKey)`

So, I have a suggestion: I guess, it would be more convenient to have a parameter like `needsMemoryCaching` to control how the images are fetched from the disk cache. Or maybe even a separate method like `getImageFromDiskForKey` which would return an image without caching it in memory.

Best regards.

**Comment by ibireme** [comment]
You may set the memory cache limit with these code:
`YYImageCache.sharedCache().memoryCache.costLimit = 20 * 1024`

or you can disable the memory cache:
`YYImageCache.sharedCache().memoryCache.countLimit = 0`

If you want get a image from disk cache, you may use:
`let key = YYWebImageManager.sharedManager().cacheKeyForURL(url)`
`let image = YYImageCache.sharedCache().diskCache.objectForKey(key) as! UIImage`

**Comment by storix** [comment]
Oh, it turns out I've overlooked the fact that by default the memory cache has no limits. I have configured the cost limit as per your suggestion and it works fine now. Thanks for clarifications!
