### ISSUE TITLE
在项目中加载WebP图片

### ISSUE THREAD

**Issue by zhouzizi** [ibireme/YYWebImage#11]
项目中加入了WebP.framework ,但是webp图片还是无法显示，请问还需要其他什么操作呢？

**Comment by zhouzizi** [comment]
![image](https://cloud.githubusercontent.com/assets/9103749/11174424/336ad7ae-8c5e-11e5-8e22-e4c4b1e65892.png)

**Comment by ibireme** [comment]
检测你的代码中是否能引用到 `webp/demux.h`:

    #import <webp/demux.h>
    #import "webp/demux.h"

如果你的项目中，用上面的其中一行代码，能正确引用，那 WebP 就可用了。
如果没有，你可能需要在编辑配置里 `Framework Search Paths` 中手动添加对应 framework 的路径。

**Comment by zhouzizi** [comment]
在 ``` Build Phases ```-》``` Link Binary With Liararies ``` 中添加了WebP. framework ,而且``` Framework Search Paths ``` 也自动添加对应的路径了、但是还是不能显示。。

**Comment by ibireme** [comment]
那在你的代码中用 `#import <webp/demux.h>` 能引用到头文件吗？

**Comment by zhouzizi** [comment]
我的项目是Swift，在桥接文件中 添加``` #import <webp/demux.h>``` 报错

**Comment by ibireme** [comment]
那说明 `Framework Search Paths` 没有添加正确。。这个里面应该添加 WebP.framework 的父目录路径。

如果还有问题，推荐用 CocoaPods 安装。

**Comment by zhouzizi** [comment]
发现在桥接文件中， 添加``` #import <webp/demux.h>``` 报错 ，但是添加``` #import <webp/encode.h>``` 正常编译，但是依旧无法显示图片

**Comment by ibireme** [comment]
你可以调用 YYImageWebPAvailable() 来判断 WebP 是否已经开启，如果已经开启，那么应该是 WebP 的格式问题、网络问题或者SSL 问题等导致的。

**Comment by zhouzizi** [comment]
重新导入YYKit后可以使用了。。。
