### ISSUE TITLE
项目里所有的 webp 解析出来的 image均为空(nil)， 同 #11，但原因似乎不同, android 使用 Fresco解析正常

### ISSUE THREAD

**Issue by btxkenshin** [ibireme/YYWebImage#111]
[notdisplay_1.webp.zip](https://github.com/ibireme/YYWebImage/files/319987/notdisplay_1.webp.zip)

RT, 服务器使用的图片是七牛那边转换为webp格式的，之前一直使用 SDWebImage 可以正常显示。
尝试使用 `YYImage` 或者直接使用 `YYWebImage` 均获取到空的图片。

1. 我看了[#11](https://github.com/ibireme/YYImage/issues/11)，并且 在引用到了`VP8_STATUS_NOT_ENOUGH_DATA`做判断的地方都打了断点，并没有走到：
``` YYCGImageCreateWithWebPData 和 _newUnblendedImageAtIndex ```

2. `YYImageDecoder` 通过 `_frameAtIndex` 获取到的 `YYImageFrame` 为 nil, 跟进去看到 `frame.blendFromIndex = 1`，同时` frame.index = 0`，导致不会走以下循环
```
for (uint32_t i = (uint32_t)frame.blendFromIndex; i <= (uint32_t)frame.index; i++) {
                if (i == frame.index) {
                    if (!imageRef) imageRef = [self _newBlendedImageWithFrame:frame];
                } else {
                    [self _blendImageWithFrame:_frames[i]];
                }
            }
```
最终走到空的 `imageRef`
```
if (!imageRef) return nil;
```

3. 另外尝试了服务器提供的 webp 格式的动图，一样无法解析，没有跟进，推测跟静态 webp 解析失败有关
4. 同样的静态 webp 和动态 webp，android 那边使用 facebook 开源的Fresco均能正常解析显示

**Comment by ibireme** [comment]
合并至：https://github.com/ibireme/YYImage/issues/37
