### ISSUE TITLE
使用了 YYWebImage 导致了CPU 使用率过高的问题。

### ISSUE THREAD

**Issue by mcmengchen** [ibireme/YYWebImage#112]
+ 在一个列表界面中的图片展示使用的是 YYWebImage，滑动的很流畅，但是发现 CPU 的使用率过高，峰值在 release 的情况下能达到110，在 Prifile 中定位了一下，都是
```
- (void)setImage:(UIImage *)image imageData:(NSData *)imageData forKey:(NSString *)key withType:(YYImageCacheType)type 
```
这个方法非常耗时，请问能否有降低的方法。

**Comment by ibireme** [comment]
能问下你列表中图片格式是什么吗？是否是静态的 GIF 或 WebP？

**Comment by mcmengchen** [comment]
都是 jpg 的图片。 @ibireme

**Comment by ibireme** [comment]
把 instruments 里耗时的上下调用栈贴一下吧，光看这一句不好定位。

**Comment by mcmengchen** [comment]
![1](https://cloud.githubusercontent.com/assets/9442979/16228075/6e2422c6-37e7-11e6-8323-27a42fa37911.png)
![2](https://cloud.githubusercontent.com/assets/9442979/16228079/706fc3be-37e7-11e6-9b14-a00d8ee19d49.png)
![2 1](https://cloud.githubusercontent.com/assets/9442979/16228083/7863fd4c-37e7-11e6-85e0-5a35dcd5cc78.png)
![2 2](https://cloud.githubusercontent.com/assets/9442979/16228085/7ae59ed6-37e7-11e6-89d3-89ec6ae3db3b.png)
![2 3](https://cloud.githubusercontent.com/assets/9442979/16228087/7d2bebc8-37e7-11e6-89a7-0eb998fbc89a.png)
![3 1](https://cloud.githubusercontent.com/assets/9442979/16228378/3e689920-37e9-11e6-80db-44059fbe6545.png)
![3 2](https://cloud.githubusercontent.com/assets/9442979/16228382/42f9052e-37e9-11e6-92d4-f070ec2aab86.png)
![3 3](https://cloud.githubusercontent.com/assets/9442979/16228385/450b88c8-37e9-11e6-8aec-f3b6a7549bdb.png)

@ibireme

**Comment by ibireme** [comment]
看了下，你应该是添加了 transform block，内部进行了一个 resize，这样图片会被重新绘制（原始数据会被丢弃），之后在保存到磁盘缓存时会重新进行编码，压缩为 PNG。

如果没有必要，不太建议对图片进行 resize 操作，直接把图片放到 ImageView 里，让 view 来调整大小效率会高很多。

**Comment by mcmengchen** [comment]
嗯，谢谢。 @ibireme
