### ISSUE TITLE
YYWebImage is not extensions safe

### ISSUE THREAD

**Issue by LnsooXD** [ibireme/YYWebImage#117]
When I use YYWebImage in today extension, the xcode has a warning:

`ld: warning: linking against a dylib which is not safe for use in application extensions: YYWebImage.framework/YYWebImage`

**Comment by ibireme** [comment]
<img width="646" alt="2016-07-01 9 10 20" src="https://cloud.githubusercontent.com/assets/839283/16522421/48b2141c-3fd0-11e6-9e70-4d2045be127e.png">

YYWebImage's code is extension safe, you may try set this setting `YES`.
