### ISSUE TITLE
YYAnimatedImage Protocol使用问题

### ISSUE THREAD

**Issue by wangqianzhou** [ibireme/YYWebImage#118]
- (CGRect)animatedImageContentsRectAtIndex:(NSUInteger)index; 方法是optional的， YYAnimatedImageView中使用时没有respondsToSelector:检查

**Comment by ibireme** [comment]
是有检查的，你可以搜一下 animatedImageContentsRectAtIndex

**Comment by wangqianzhou** [comment]
_curImageHasContentsRect记录了是否respondsToSelector
