### ISSUE TITLE
使用yy_imageByRoundCornerRadius:处理特定图片不起作用

### ISSUE THREAD

**Issue by zyi1992** [ibireme/YYWebImage#119]
图片的url 是  http://www.gosugamers.net/uploads/images/players/107973-1451992759.jpeg   请求到图片后用yy_imageByRoundCornerRadius:处理  图片处理后的size和处理前的size是一样的  半径设的为2000.处理其他图片是都没有问题

**Comment by ibireme** [comment]
<img width="203" alt="2016-07-15 11 54 27" src="https://cloud.githubusercontent.com/assets/839283/16880371/81528366-4ae7-11e6-8b89-86eb33bfe1d5.png">

试了一下是可以的啊。

**Comment by zyi1992** [comment]
这个不是圆的吧。。。。

**Comment by zyi1992** [comment]
长方形切完整圆必须要先处理成正方形才可以吗？

**Comment by ibireme** [comment]
这个方法是 round corner 啊，只是处理圆角。
