### ISSUE TITLE
集成报错

### ISSUE THREAD

**Issue by zyvv** [ibireme/YYWebImage#12]
为什么我集成会报"Enumerator value evaluates to -1，which cannot be narrowed to type ‘NSUInteger’(aka 'unsigned long')"，要怎么解决呢？
我是用unity打出来的工程。

**Comment by ibireme** [comment]
头文件里有一处 enum 声明类型有问题。C++ 对类型检测更严格，所以报错了。

目前已经修正，请更新代码或 pod 再试试看。

**Comment by zyvv** [comment]
已经解决了，谢谢~~
