### ISSUE TITLE
https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYWebImageOperation.m#L509-L511

### ISSUE THREAD

**Issue by SinCheung** [ibireme/YYWebImage#122]
https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYWebImageOperation.m#L509-L511,
这里if ([self isCancelled]) _progress(0, _expectedSize);已经取消了，还需要继续处理progress的任务吗，
if (![self isCancelled]) _progress(0, _expectedSize);这样？

**Comment by ibireme** [comment]
嗯，这好像是个 bug。。

**Comment by ibireme** [comment]
Fixed
