### ISSUE TITLE
从缓存里获取图片的问题

### ISSUE THREAD

**Issue by bringbird** [ibireme/YYWebImage#125]
‘UIImage *image = [[YYImageCache sharedCache] getImageForKey:imageurl]‘
这个根据‘key’获取缓存的图片，这个‘key’指的是图片的url还是什么呢？
我记得 SD 的是url，不知道在‘YYImageCache’是不是一样？

**Comment by ibireme** [comment]
[[YYWebImageManager sharedManager] cacheKeyForURL:url]
