### ISSUE TITLE
Add support for App Extension target 

### ISSUE THREAD

**Issue by skyline75489** [ibireme/YYWebImage#13]
Similar issue as https://github.com/ibireme/YYCategories/issues/3

**Comment by ibireme** [comment]
Added.
You may add `YY_TARGET_IS_EXTENSION` flag in `Build Settings` - `Preprocessor Macros` sections.

**Comment by skyline75489** [comment]
AFNetwoking is using `NS_EXTENSION_UNAVAILABLE_IOS` marco to support Extension target. The PR is [here](https://github.com/AFNetworking/AFNetworking/pull/2737/files). It allows same code for both app and extension target without defining `AF_APP_EXTENSIONS`  marco.  I think maybe this is a better way.

**Comment by Natoto** [comment]
can't find YYWebImage in pod

**Comment by ibireme** [comment]
Use `pod update --verbose` to update your pod list

**Comment by ibireme** [comment]
I tried `NS_EXTENSION_UNAVAILABLE_IOS` but it can only be used in compile time for single method.
Inspired by [SDWebImage](https://github.com/rs/SDWebImage/issues/1082), I use runtime to detect App Extension target: [commit 7500348](https://github.com/ibireme/YYWebImage/commit/7500348748f49f7b0e05bd3b76ce9904e5df9112).

**Comment by skyline75489** [comment]
Nice approach. I'll close this. Cheers!
