### ISSUE TITLE
关于[[NSURLConnection alloc] initWithRequest:_request delegate:[_YYWebImageWeakProxy proxyWithTarget:self]]有些疑惑？

### ISSUE THREAD

**Issue by xiabob** [ibireme/YYWebImage#130]
[[NSURLConnection alloc] initWithRequest:_request delegate:[_YYWebImageWeakProxy proxyWithTarget:self]]
看了https://github.com/ibireme/YYWebImage/issues/43 还是觉得有点问题，不知道是不是我理解错了。
如果NSURLConnection的delegate是weak，这样使用会不会被直接释放掉，导致代理的方法无法调用。另外：在https://developer.apple.com/reference/foundation/nsurlconnection/1414520-initwithrequest?language=objc 里面Special Considerations部分：
During the download the connection maintains a strong reference to the delegate. It releases that strong reference when the connection finishes loading, fails, or is canceled.
不知道应该如何理解这个download？

**Comment by HoneyLuka** [comment]
我觉得就像你说的，文档有说在下载过程中会保持强引用，下载结束后会释放。猜测就是设置进去的时候retain了一下，然后在请求结束的时候release。

**Comment by ibireme** [comment]
self(YYWebImageOperation) 是被其他地方持有的，所以不会释放掉。如果 YYWebImageOperation 的持有者释放了它，那这样就可以让 Connection 直接取消并释放。
