### ISSUE TITLE
你好，请问有没有只进行磁盘缓存不进行内存缓存的功能？

### ISSUE THREAD

**Issue by engebei** [ibireme/YYWebImage#14]
你好，请问有没有只进行磁盘缓存不进行内存缓存的功能？

**Comment by ibireme** [comment]
目前没有。。。
如果你需要禁用内存缓存，可以调用 `[YYWebImageManager sharedManager].imageCache.memoryCache.countLimit = 0; `，也可以子类化 YYImageCache 然后把 memoryCache 设为 nil。

请问禁用内存缓存是什么使用场景？

**Comment by engebei** [comment]
这样也可以，谢谢
