### ISSUE TITLE
YYWebImageManager download image in order

### ISSUE THREAD

**Issue by ducminh1012** [ibireme/YYWebImage#153]
Hi everyone,
I want to download images from an array of image_urls.
How can I put it in the same order with the image_urls?
Currently, I use this code, but it's not come in order.

<img width="613" alt="screen shot 2016-12-15 at 10 33 07 am" src="https://cloud.githubusercontent.com/assets/12797262/21210958/e7f224e0-c2b1-11e6-93b2-f363035e43c6.png">

Thanks.

**Comment by CodeLife2012** [comment]
You can resort the images when download finished; This issue is not about this project, I think you can ask it in stackoverflow.

**Comment by ducminh1012** [comment]
Achieved, thanks for your solution.
