### ISSUE TITLE
CocoaPod加入YYWebImage后报错

### ISSUE THREAD

**Issue by hxverygood** [ibireme/YYWebImage#17]
报错信息：
ld: 639 duplicate symbols for architecture x86_64
linker command failed with exit code 1 (use -v to see invocation)

我的Podfile：
platform :ios,'8.0'
pod 'ReactiveCocoa', '~>2.5'
pod 'YTKKeyValueStore', '~>0.1.2'
pod 'MJExtension'
pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
pod 'Masonry', '~> 0.6.3'
pod 'YYModel'
pod 'YYWebImage'
use_frameworks!

**Comment by ibireme** [comment]
我测试了以上 Podfile，没有报错。
请 Clean 工程、清空 Derived Data 后，用 `pod install --verbose` 或 `pod update --verbose` 更新 pod 并查看 log。

**Comment by jiazufei** [comment]
楼主问题解决了吗？

**Comment by heji** [comment]
同问，我这边是编译报错，应该是WebP.framework的问题

**Comment by ibireme** [comment]
如果是 CocoaPods 安装时 WebP 组件导致有冲突，目前只能改用 Carthage 或者手动安装了。。。

为了支持 WebP 动图的编码和解码，现在这个 Vendor/WebP.framework 在编译时包含了 mux 和 demux 模块，编译脚本也在 Vendor 目录里。 YYWebImage 在编译时会根据 WebP 的头文件自动开启或禁用 WebP 编解码功能。

**Comment by hxverygood** [comment]
报告ibireme，我的问题解决了，不是YYWebImage的问题。
之前少测试了一步：新建个工程用我的Podfile就没问题。
这个报错隐蔽，最后才发现是我之前加入“银联”的库文件有问题，银联也在官方文档上有说明，已解决。
实在是麻烦ibireme了，抱歉！
