### ISSUE TITLE
YYWebImageStage状态有时候返回两个0(YYWebImageStageCancelled)

### ISSUE THREAD

**Issue by jdk89757** [ibireme/YYWebImage#18]
使用下面这个方法
- (void)yy_setImageWithURL:(NSURL *)imageURL
               placeholder:(UIImage *)placeholder
                   options:(YYWebImageOptions)options
                completion:(YYWebImageCompletionBlock)completion;
应用从后台到前台过程中调用的时候,发现YYWebImageStage返回的状态一直是0,不知道为什么?是不是使用方法有问题?

**Comment by ibireme** [comment]
YYWebImageStageCancelled 表示图片异步加载的 NSOperation 被取消了，这有几种可能：
* 手动调用了 yy_cancelCurrentImageRequest 方法
* 当前已经有一个异步加载 NSOperation 正在进行中，此时又调用了 yy_setImageXXX 等方法。
* 当前已经有一个异步加载 NSOperation 正在进行中，但图片视图被释放了。

通常来说，回调里只需要处理 YYWebImageStageFinished（成功或失败）这种状态即可。

设置图片时，可以加上参数 YYWebImageOptionAllowBackgroundTask 来允许后台下载图片，但我个人不太推荐。。。

**Comment by jdk89757** [comment]
@ibireme 谢谢你的细心解答,我找到问题并成功解决了 ~ ~
