### ISSUE TITLE
用cocoapods更新时发生错误

### ISSUE THREAD

**Issue by DeveloperLx** [ibireme/YYWebImage#19]
提示如下：

Installing YYWebImage 0.9.11 (was 0.9.8)

[!] Error installing YYWebImage
[!] /usr/bin/git clone https://github.com/ibireme/YYWebImage.git /var/folders/pg/0qh5fq653wq1l3qz9_3ftg3r0000gn/T/d20151207-633-8tggww --single-branch --depth 1 --branch 0.9.11

Cloning into '/var/folders/pg/0qh5fq653wq1l3qz9_3ftg3r0000gn/T/d20151207-633-8tggww'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by ibireme** [comment]
http://stackoverflow.com/questions/26197171/git-clone-repository-error-rpc-failed-result-56-http-code-200

这个可能是你的网络问题、Github 的临时问题、或者你的本机防火墙问题。

**Comment by longxianlin** [comment]
网络很正常。pod install其它库都下载下来了
