### ISSUE TITLE
[YYWebImageOperation _networkThreadMain:] (YYWebImageOperation.m:197)

### ISSUE THREAD

**Issue by Rochester-Ting** [ibireme/YYWebImage#192]
![image](https://user-images.githubusercontent.com/16523293/27776523-e3096eec-5fdd-11e7-9d47-eed8198dd11c.png)

请问这个崩溃是YYWebImage引起的么

**Comment by ibireme** [comment]
这个线程是在 mach_msg_trap 暂停中，并不是崩溃。
这个页面里，应该有其他线程，上面有标记 crash 的，那个才是崩溃的地方。

**Comment by Rochester-Ting** [comment]
谢谢
