### ISSUE TITLE
渐进式模糊下载设置无效

### ISSUE THREAD

**Issue by Rain-dew** [ibireme/YYWebImage#193]
我设置了YYWebImageOptionProgressiveBlur类型，但是遗憾的是没有任何反应。

**Comment by rockerkekex** [comment]
同

**Comment by rushairer** [comment]
me too

**Comment by rushairer** [comment]
@Rain-dew 图片设成渐进式的了吗？

**Comment by rushairer** [comment]
二等分

**Comment by Rain-dew** [comment]
请问如何设置呢？我按照示例代码，无效的


Sent from Mail Master
在2017年07月25日 10:23，rushairer 写道：

@Rain-dew 图片设成渐进式的了吗？

**Comment by Rain-dew** [comment]
// 渐进式：边下载边显示
[imageView yy_setImageWithURL:url options:YYWebImageOptionProgressive];
	
// 渐进式加载，增加模糊效果和渐变动画 （见本页最上方的GIF演示）
[imageView yy_setImageWithURL:url options:YYWebImageOptionProgressiveBlur ｜ YYWebImageOptionSetImageWithFadeAnimation];
第二段代码无效。有没有人知道啥问题？

**Comment by rushairer** [comment]
关于渐进式图片的处理
https://www.biaodianfu.com/progressive-jpeg.html

在photoshop中有“存储为web所用格式”，打开后选择“连续”就是渐进式JPEG。

**Comment by rockerkekex** [comment]
@rushairer 只有这种图才能渐进模糊加载吗？

**Comment by Rain-dew** [comment]
也就是说，这种渐进式的模糊下载，实际上需要图片本身的支持对吧。需要在photoshop中有“存储为web所用格式”，打开后选择“连续”就是渐进式JPEG。这样就可以了对吧。感谢解答！

**Comment by rushairer** [comment]
是的。我用的七牛做图床，七牛的样式里有渐进式的选项。

**Comment by Rain-dew** [comment]
求个连接


Sent from Mail Master
在2017年07月25日 15:57，rushairer 写道：

是的。我用的七牛做图床，七牛的样式里有渐进式的选项。

**Comment by LByy** [comment]
有谁知道这个渐进式的 progressive格式的jpeg图片 是怎么做出来由模糊到清晰的效果吗？本人正在尝试自己绘制 但是效果还没有出来，谁知道请指教！！在线等
