### ISSUE TITLE
在build编译的时候经常报这个错误

### ISSUE THREAD

**Issue by yimiaodaren** [ibireme/YYWebImage#20]
![8ef3cadc-1dac-42c0-8eee-b5058965f8fd](https://cloud.githubusercontent.com/assets/5618443/11646020/7d9b0780-9d94-11e5-9932-c3dd66b92f56.png)

多编译几次或者clear一下才会成功，随机的概率，有什么好的解决办法么?

**Comment by ibireme** [comment]
请确认引入头文件时用的是 #import，另外请检查是否有其他头文件的循环、多次引用。

**Comment by yimiaodaren** [comment]
我是这么用的
    #import <YYWebImage/YYWebImage.h>
并且我是Xcode7.1

**Comment by ibireme** [comment]
这个就不太清楚了，我和其他人暂时没遇到这种情况。。
请问你是通过什么工具编译的？cocoapods、carthage、framework还是手动编译的？

**Comment by yimiaodaren** [comment]
cocoapods install的 然后xcode build

**Comment by ibireme** [comment]
我新建了一个工程，用 cocoapods 加入了 YYWebImage 没有问题。

你能给一下你的 cocoapods 版本，和 Podfile 吗？

**Comment by yimiaodaren** [comment]
0.39.0

# ignore all warnings from all pods 
inhibit_all_warnings!
platform :ios, '7.1'
pod 'YYWebImage', '~> 0.9.7'

**Comment by ibireme** [comment]
我用两台机器，相同版本的 cocoapods 测试了以上 Podfile，真机和模拟器没有问题。

请 Clear 工程、清空 Derived Data 等缓存，清空 pod，然后再尝试重新安装 pod。
如果还有问题，请检查下 pod 中相关库的依赖关系、代码中的依赖关系，是否有重复引用。

**Comment by yimiaodaren** [comment]
灰常感谢。请教一下情况pod就是把 ~/.cocoapod 给删除了么。
我发现报错的时候，这个yywebimage.h的文件，并不是我当前项目下得pods/yywebimage/里面的。
竟然指向了我在其他项目中的pods/yywebimage的文件。
我经常更新pod 用 --no-repo-update 是不是有关系呢？

**Comment by ibireme** [comment]
在连接 github 慢的时候，用 --no-repo-update 能省了更新 pod 列表的时间，但是这常常会产生各种问题。如果可能，还是不要用这个参数吧～

**Comment by yimiaodaren** [comment]
Thank you! Big shen
