### ISSUE TITLE
关于动态图片的疑问

### ISSUE THREAD

**Issue by wuxulome** [ibireme/YYWebImage#21]
您好，在使用SDWebImage的时候，不需要关心是否为动态图片，只需要新建UIImageView显示就好。但由于YYWebImage的动态图片使用YYAnimatedImageView显示，当我不知道图片格式的时候，该如何处理？是否可以图片统一都用YYAnimatedImageView显示，这样会不会影响效率？

**Comment by ibireme** [comment]
YYAnimatedImageView 是 UIImageView 的子类，可以直接作为 UIImageView 的替代：

    UIImageView *imageView = [YYAnimatedImageView new];

在不显示动态图时，效率和 UIImageView 几乎一样。

**Comment by wuxulome** [comment]
好的，非常感谢。
