### ISSUE TITLE
用cocoapods导入YYwebImage，在YYImageCoder.m下#import "YYKitMacro.h"这行file not found

### ISSUE THREAD

**Issue by ruichou** [ibireme/YYWebImage#22]
0.9.11版本的。clean，pod install ，pod update之后 依然报错

**Comment by ibireme** [comment]
请检查你的 pod 后的代码，更新时不要加 --no-repo-update。

目前 https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/Image/YYImageCoder.m 这个文件里面没有 "YYKitMacro.h" 这一行。

**Comment by ruichou** [comment]
我重建了一个Test导入YYwebImage  没问题了，我去看我这个YYImageCoder.m里面还真的没这个了，两个结构不一样，好奇怪，是cocoapods出问题了嘛。另外，同是90后，我佩服你！太厉害，我周围人都在学你的YYkit。

 YYImageCoder.m
//  YYKit <https://github.com/ibireme/YYKit>
//
//  Created by ibireme on 15/5/13.
//  Copyright (c) 2015 ibireme.
//
//  This source code is licensed under the MIT-style license found in the
//  LICENSE file in the root directory of this source tree.
//

#import "YYImageCoder.h"
#import <CoreFoundation/CoreFoundation.h>
#import <ImageIO/ImageIO.h>
#import <Accelerate/Accelerate.h>
#import <QuartzCore/QuartzCore.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <AssetsLibrary/AssetsLibrary.h>
#import <objc/runtime.h>
#import <pthread.h>
#import <libkern/OSAtomic.h>
#import <zlib.h>
#import "YYImage.h"
#import "YYKitMacro.h"  //就在这一行  好奇怪啊

#ifndef YYIMAGE_WEBP_ENABLED
#if __has_include(<webp/decode.h>) && __has_include(<webp/encode.h>) && \

**Comment by ibireme** [comment]
这个代码是 YYKit 的，YYKit 包含 YYWebImage，你可以检查下依赖关系。
