### ISSUE TITLE
YYWebImageOperation设计的一点小疑问

### ISSUE THREAD

**Issue by L0omg** [ibireme/YYWebImage#24]
你好，请问为什么_startOperation、_cancelOperation、_startRequest等操作都要切到一个线程中执行呢？

**Comment by ibireme** [comment]
主要是出于性能考虑，避免这些操作阻塞其他线程。
另一方面，这样可以让所有网络操作都集中在一个网络线程内，避免各种多线程的额外处理。

**Comment by L0omg** [comment]
恩，明白，谢谢。还有几个疑问：
1、如果批量下载时，这些图片的下载任务应该会互相阻塞吧，这样对效率会有影响吧？
2、所有的操作都集中在_networkThread和_imageQueue，那么为什么还要使用NSOperation去创建线程呢？

**Comment by ibireme** [comment]
network 里面主要是些简单的操作，不会占用太多的资源，相对于网络请求的 delegate 调用频率来说，network 里的操作不会产生阻塞。

imageQueue 实际上是由多个 serial queue 组成的，这样也能充分利用 CPU 资源，并且图片解码这种东西，太多并发反而会造成资源浪费，也不能缩短总 CPU 占用时间。

NSOperation 是用来管理每个 image 请求的，它是对外的更上层一些的封装，便于开发者使用和全局控制。

**Comment by L0omg** [comment]
哦，谢谢解答，明白了。
