### ISSUE TITLE
如何加载高清大图分辨率10000+以上的图片

### ISSUE THREAD

**Issue by lkqin** [ibireme/YYWebImage#26]
加载一张类似新浪微博长图的时候崩溃退出 使用 0.9.1版本
使用的
imageview.yy_setImageWithURL(NSURL(string: allimageurl), placeholder: UIImage())
报错代码  
CGContextDrawImage(context, CGRectMake(0, 0, width, height), imageRef); // decode
CGImageRef imageRefExtended = YYCGImageCreateDecodedCopy(imageRef, YES);
CGImageRef imageRef = [self _newUnblendedImageAtIndex:index extendToCanvas:extendToCanvas decoded:&decoded];
result = [self _frameAtIndex:index decodeForDisplay:decodeForDisplay];

+ (void)_networkThreadMain:(id)object {
    @autoreleasepool {
        [[NSThread currentThread] setName:@"com.ibireme.webimage.request"];
        NSRunLoop *runLoop = [NSRunLoop currentRunLoop];
        [runLoop addPort:[NSMachPort port] forMode:NSDefaultRunLoopMode];
        [runLoop run]; //这行报错
    }
}

**Comment by ibireme** [comment]
可以参考苹果官方例子：
https://developer.apple.com/library/ios/samplecode/LargeImageDownsizing/
