### ISSUE TITLE
pod 'YYWebImage' 的时候，报错了。

### ISSUE THREAD

**Issue by ShengQiangLiu** [ibireme/YYWebImage#27]
[!] The 'Pods' target has frameworks with conflicting names: WebP.

**Comment by ibireme** [comment]
WebP 冲突。

检查你其他的库是否引入了 WebP 组件，如果有，则去掉。
如果你不愿意用 YYWebImage 自带的 WebP 组件，则需要换用 Carthage 或者手动安装。

**Comment by ibireme** [comment]
无回复则先关闭问题，稍后未解决可以再次开启。
