### ISSUE TITLE
YYAnimagedImage？是不是打错了?

### ISSUE THREAD

**Issue by yxztj** [ibireme/YYWebImage#29]
YYAnimagedImageView.m:
typedef NS_ENUM(NSUInteger, YYAnimagedImageType) {
    YYAnimagedImageTypeNone = 0,
    YYAnimagedImageTypeImage,
    YYAnimagedImageTypeHighlightedImage,
    YYAnimagedImageTypeImages,
    YYAnimagedImageTypeHighlightedImages,
};

是不是打错了？

**Comment by ibireme** [comment]
感谢指正🙏
好在不影响对外的 API，我稍后改一下。

**Comment by ibireme** [comment]
https://github.com/ibireme/YYWebImage/commit/49b9e49c624a3d927bb7304c4fe47a7b4ff05c17
