### ISSUE TITLE
请问有没有手动清理磁盘或者缓存的方法？

### ISSUE THREAD

**Issue by borischou** [ibireme/YYWebImage#3]
SDWebImage里有clearDisk/cleanDisk/clearMemory等方法，但我在YY里好像没找到。所以想知道如果开销过大需要自动或者手动调用清理缓存或者内存告警的时候应该怎么做，谢谢。

**Comment by ibireme** [comment]
YYImageCache *cache = [YYWebImageManager sharedManager].cache;
	[cache.memoryCache removeAllObjects];
	[cache.diskCache removeAllObjects];

收到内存警告时，内存缓存默认会自动清空。
详情可以见 `YYMemoryCache` 和 `YYDiskCache` 两个类。
