### ISSUE TITLE
YYAnimatedImageView没有initWithFrame方法

### ISSUE THREAD

**Issue by yxztj** [ibireme/YYWebImage#30]
使用Swift:
let imageView = YYAnimatedImageView(frame: CGRectZero)
由于没有定义initWithFrame方法，虽然imageView成功创建，但是由于没有初始化ivar(_runloopMode和_autoPlayAnimatedImage)，图片不会自动播放。
希望能加上。

**Comment by ibireme** [comment]
这个应该在一个月之前改过了：https://github.com/ibireme/YYWebImage/commit/46c7fb5814573ad987b8d711b0259ed2a2c12df1
更新下代码看看～

**Comment by yxztj** [comment]
感谢快速回复！我去更新一下代码 :)
