### ISSUE TITLE
直接保存UIImageView里面的image到系统相册出现模糊的问题。

### ISSUE THREAD

**Issue by xd54622** [ibireme/YYWebImage#32]
我用YYWebImage加载一个图片到UIImageView，然后直接保存UIImgeView的属性image到相册，去相册查看的时候发现模糊。这是什么问题呢？我看了一下UIImageView+YYWebImage.h里面也是直接对UIImageView的image进行赋值的啊。还有一个问题，如果是继承YYAnimatedImageView的话，保存图片是不是应该先从YYImageCache里面根据url获得image，然后再去保存？

**Comment by ibireme** [comment]
你可以看看这个方法：https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/Image/YYImageCoder.m#L2766-L2781

直接取 image 是没问题的，你可能需要检查一下保存时是否进行了其他操作。

**Comment by xd54622** [comment]
我检查了一下，我这边保存的时候，要加水印。所以要对image进行合成一张水印图片。但是同样都是要加水印，我用
NSData * data = [NSData dataWithContentsOfURL:[NSURL URLWithString:imageUrl]];
UIImage * imagebg = [UIImage imageWithData:data];
然后拿这个imaging去加水印之后，保存到相册，就是要比直接用UIImageView.image去加水印要清楚一些，好奇怪。

**Comment by xd54622** [comment]
不过有个问题是，这个imageUrl是需要裁剪一下，就是通过七牛在url后面加一个参数，进行裁剪。但是这个imageUrl都是给的是加了裁剪参数之后的。也是说是同样的url，一个用nsdata下载，一个用yy去下载。

**Comment by ibireme** [comment]
那这个你可能要检查一下加水印的方法内部实现了，这个我帮不上忙了。。

**Comment by xd54622** [comment]
//保存到相册
UIImageWriteToSavedPhotosAlbum(imageView.image, nil, nil, nil);
[waterMarkImage saveImageToAlbumWithWatermark:imageView.image];
好哒，真不好意思，还是我自己的问题。我用UIImageView.image进行直接保存和加水印保存，发现加了水印之后变模糊了，所以应该是我这边的问题。
真不好意思，打扰了喔，还有，谢谢ibireme，好热心，回复的好快。
