### ISSUE TITLE
Transform block sometimes not work

### ISSUE THREAD

**Issue by xspyhack** [ibireme/YYWebImage#34]
``` Objective-C
 - (void)yy_setImageWithURL:(NSURL *)imageURL
               placeholder:(UIImage *)placeholder
                   options:(YYWebImageOptions)options
                  progress:(YYWebImageProgressBlock)progress
                 transform:(YYWebImageTransformBlock)transform
                completion:(YYWebImageCompletionBlock)completion;
```

The transform block doesn't invoke **sometimes** when I use this method.

**Comment by ibireme** [comment]
This block will be invoked once only if the image is loaded from remote/local URL.

**Comment by xspyhack** [comment]
When I resize and round the image in transform block in UICollectionViewCell, there are some images haven't be resized and rounded and others had be resized and rounded. I am sure all image load from remote are the same size.

**Comment by ibireme** [comment]
I recommend to use a custom image manager with another image cache to store the transformed images.

For example:
https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusHelper.m#L81-L94
https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusCell.m#L754-L760

You man clear your image cache, and run your code again to see the result.

**Comment by xspyhack** [comment]
Great, thanks a lot.

**Comment by xspyhack** [comment]
The problem remains unresolved after use your recommend way.
And it is hardly to find the problem.
