### ISSUE TITLE
YYWebImageManager中incrementNetworkActivityCount方法每次都会新起一个NSTimer会不会产生额外的开销呢?

### ISSUE THREAD

**Issue by crossPQW** [ibireme/YYWebImage#35]
可不可以新建一个全局的`Timer`,然后在合适的时候通过`setFireData`来调度timer的开始与暂停,会不会减少内存的开销呃?
PS:`[timer  invalidate]`这个方法好像在我的项目中并不会成功的销毁timer,还需要手动置nil才可以,不知道你这里会不会存在这个问题.

**Comment by ibireme** [comment]
这个 timer 就是全局的。
另外，调用 `[timer invalidate]` 后，timer 会失效，但它何时被释放就取决于对象的生命周期了。这里用到的 timer，何时释放倒是无所谓。

**Comment by crossPQW** [comment]
在`_changeNetworkActivityCount`中,这一句`info.timer = [NSTimer timerWithTimeInterval:kNetworkIndicatorDelay target:self selector:@selector(_delaySetActivity:) userInfo:@(info.count > 0) repeats:NO];
`会不会每次调用都生成一个`NSTimer`呃,`_YYWebImageApplicationNetworkIndicatorInfo`拥有这个`timer`属性,在这个类初始化的时候执行`timer = [NSTimer timerWithTimeInterval:kNetworkIndicatorDelay target:self selector:@selector(_delaySetActivity:) userInfo:@(info.count > 0) repeats:NO];`
求回复哈:D

**Comment by crossPQW** [comment]
在`_changeNetworkActivityCount`中,这一句`info.timer = [NSTimer timerWithTimeInterval:kNetworkIndicatorDelay target:self selector:@selector(_delaySetActivity:) userInfo:@(info.count > 0) repeats:NO];
`会不会每次调用都生成一个`NSTimer`呃,`_YYWebImageApplicationNetworkIndicatorInfo`拥有这个`timer`属性,在这个类初始化的时候执行`timer = [NSTimer timerWithTimeInterval:kNetworkIndicatorDelay target:self selector:@selector(_delaySetActivity:) userInfo:@(info.count > 0) repeats:NO];`，我的目的就是不需要每次都去创建一个新的｀nastier｀
求回复哈😄

**Comment by ibireme** [comment]
我猜你可能担心两个地方：内存占用和CPU消耗。

1. 内存占用
全局最多只会存在一个 Timer，所以内存占用不会增长。

2. CPU 消耗
看下苹果文档：

> You can set this property to adjust the firing time of a repeating timer. Although resetting a timer’s next firing time is a relatively expensive operation, it may be more efficient in some situations. For example, you could use it in situations where you want to repeat an action multiple times in the future, but at irregular time intervals. Adjusting the firing time of a single timer would likely incur less expense than creating multiple timer objects, scheduling each one on a run loop, and then destroying them.

苹果说，设置 fire time 也是要花费不少资源的，但"可能"会比创建"多个" timer 消耗资源少。我还没实际测试性能，所以换为通过 fire time 来复用 timer 是否能减少资源消耗，我也不太确定，这块儿可以尝试 benchmark 看一下。

就实际情况来说，这个 timer 操作的消耗，是远少于其他图片设置方法调用的消耗的，一般情况下不用担心。看看 [AFNetworking](https://github.com/AFNetworking/AFNetworking/blob/master/UIKit%2BAFNetworking/AFNetworkActivityIndicatorManager.m)，它甚至用到了两个 timer，看起来似乎没有产生性能问题。

**Comment by crossPQW** [comment]
太棒了.......所以我以后还是要多查一下文档
