### ISSUE TITLE
发现一个问题，就是大量图片加载崩溃的问题

### ISSUE THREAD

**Issue by af8229** [ibireme/YYWebImage#38]
内存太大然后崩溃了，之前用SDWebimage也有这个问题，就是大量图片没有调用到didRevecive方法直接崩溃，有啥处理办法嘛  我目前的处理办法是每次push操作都会做一次clear内存的操作

**Comment by ibireme** [comment]
不太清楚 didRevecive、push、clear 操作是什么。。

图片解码后，肯定会占用大量的内存，图片库也无法保证内存占用会有多少，所以还是要靠开发者手动控制。
