### ISSUE TITLE
新版本里长时间加载大量图片后无法显示

### ISSUE THREAD

**Issue by xilin** [ibireme/YYWebImage#39]
更新了0.9.12之后，长时间使用应用，加载了比较多的图片（文件大小大概20M+）之后图片都无法显示了，只能显示placeholder。
0.9.11没有这个问题。
不知道和新版的这个[commit](https://github.com/ibireme/YYWebImage/commit/f431eb314378bc1badf914a888de1a552a379a64)引入的弱引用有没有关系？

测试设备是6s和4s，都有这种情况。

**Comment by ibireme** [comment]
我仔细看了下从 0.9.11 到 0.9.12 的改动，应该没有引起这种问题的地方啊。。

你可以试试在 completion:(YYWebImageCompletionBlock)completion 里打印一下 image, url, from, stage, error 这几个值看一下。

**Comment by xilin** [comment]
我加了几个日志之后测试妹子表示无法复现了= =我节后再试试看。
