### ISSUE TITLE
Suggestion : Changing UIImageView border color and size

### ISSUE THREAD

**Issue by alaaghribi** [ibireme/YYWebImage#4]
Hi,
Thank you for this awesome framework.
I'm manually adding a border color for the `UIImageView` downloaded using this code :    
 CALayer * l = [imageView layer];
    [l setBorderWidth:1.0];
    [l setBorderColor:[[UIColor greenColor] CGColor]];    

My suggestion, can you add the possibility to change the border color and border width in that method:
`- (UIImage *)yy_imageByRoundCornerRadius:(CGFloat)radius`

Thanks .

**Comment by ibireme** [comment]
Added: 
https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/Categories/UIImage%2BYYWebImage.h#L153-L168

**Comment by alaaghribi** [comment]
That was so fast ! You're the best ;)!

**Comment by alaaghribi** [comment]
Can you please update the Cocoapods version to include that change?

**Comment by ibireme** [comment]
Updated ~
