### ISSUE TITLE
渐进式加载YYWebImageStageProgress有时加载不出图片

### ISSUE THREAD

**Issue by Pr-Chen** [ibireme/YYWebImage#42]
如果有好几个图片要加载,貌似100%不行,
    [self.imageView1 yy_setImageWithURL:url1 options:YYWebImageStageProgress];
    [self.imageView2 yy_setImageWithURL:url2 options:YYWebImageStageProgress];
    [self.imageView3 yy_setImageWithURL:url3 options:YYWebImageStageProgress];
全部加载不出来.
不知是我xcode的bug还是确实是代码的问题.

**Comment by ibireme** [comment]
不用任何 options 时呢？

**Comment by Pr-Chen** [comment]
不用的时候正常, options为多个混合选项的时候也没问题, 只为YYWebImageStageProgress有问题.暂时是发现这样的问题.

**Comment by ibireme** [comment]
看代码暂时还没发现问题。。
你可以试试在 completion:(YYWebImageCompletionBlock)completion 里打印一下 image, url, from, stage, error 这几个值看一下。

**Comment by Pr-Chen** [comment]
自动打印的信息  Can't endBackgroundTask: no background task exists with identifier 1, or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

**Comment by ibireme** [comment]
上面这个，是启用了 YYWebImageOptionAllowBackgroundTask 参数吧。。这个与图片显示倒是没关系。。
