### ISSUE TITLE
为什么NSURLCollection在设置delegate的时候不直接使用delegate,而是使用YYWebImageWeakProxy这个类重写基类的方法呢?

### ISSUE THREAD

**Issue by crossPQW** [ibireme/YYWebImage#43]
hello,我在读你的源码的时候对这块比较疑惑,不是很清楚这么做的用意是什么?这么写跟我们平常直接通过一个weak的delegate属性设置代理有什么区别么?麻烦能否解惑一下呢
```
 _connection = [[NSURLConnection alloc] initWithRequest:_request delegate:[_YYWebImageWeakProxy proxyWithTarget:self]];
```

**Comment by ibireme** [comment]
NSURLConnection 文档里并没有说明这个 delegate 在其内部的属性是 strong、weak 或是 assign。这里把 delegate 封装到 WeakProxy 里，能保证在各种情况下都不会出问题。

**Comment by crossPQW** [comment]
OK,多谢解惑

**Comment by xiabob** [comment]
如果NSURLConnection的delegate是weak，这样使用会不会被直接释放掉。另外：在https://developer.apple.com/reference/foundation/nsurlconnection/1414520-initwithrequest?language=objc 里面Special Considerations部分：
During the download the connection maintains a strong reference to the delegate. It releases that strong reference when the connection finishes loading, fails, or is canceled.
不知道应该如何理解这个download？
