### ISSUE TITLE
YYImageCache 没有清空缓存和计算总缓存大小的方法

### ISSUE THREAD

**Issue by lexiaoyao20** [ibireme/YYWebImage#44]
如题，能不能添加如下面 SDImageCache 类似的方法啊
```
[[SDImageCache sharedImageCache] clearMemory];
    [[SDImageCache sharedImageCache] cleanDisk];

/**
 * Get the size used by the disk cache
 */
- (NSUInteger)getSize;

/**
 * Get the number of images in the disk cache
 */
- (NSUInteger)getDiskCount;
```

**Comment by ibireme** [comment]
YYImageCache *imageCache = [YYWebImageManager sharedManager].cache;
    
    // get size:
    imageCache.memoryCache.totalCount;
    imageCache.diskCache.totalCount;
    imageCache.diskCache.totalCost;
    
    // clear:
    [imageCache.memoryCache removeAllObjects];
    [imageCache.diskCache removeAllObjects];
    
    // clear with progress
    [imageCache.diskCache removeAllObjectsWithProgressBlock:^(int removedCount, int totalCount) {
        CGFloat progress = removedCount / (float)totalCount;
    } endBlock:^(BOOL error) {
        // success
    }];

**Comment by lexiaoyao20** [comment]
好的，谢谢
