### ISSUE TITLE
请教两个问题，

### ISSUE THREAD

**Issue by lynn87** [ibireme/YYWebImage#45]
1.YYWebImage和SDWebImage如果下载图片完成之后需要处理图片的话（比如圆角，裁切，模糊）都是把处理后的图片缓存到沙盒和内存，但是感觉这样不太好，比如对于同一个用户的头像，有些地方需要圆角，有些地方不需要圆角，有些地方头像尺寸比较大，有些地方头像尺寸比较小，但是这些图的原图都是同一个url所得，造成处理困难，或者用你在YYKit的DEMO里的写法，写几个不同的AvatarManager，但是这样的话对于原图是同一张的图片需要缓存很多份处理后的图片，很占沙盒和内存资源，针对该场景有更好的方案么？
2.个人感觉现在的主流图片下载库都有两个问题，
        (1).内存占用控制的不太好，都是在收到内存警告的时候清空内存级缓存 
        (2).在一个界面销毁的时候也不取消该界面产生的图片请求，浪费不必要的用户流量
 如果用Method Swizzling把UIImageView的dealloc方法替换掉，在调用系统dealloc之前做两件事，清空该ImageView请求产生的内存级缓存以及取消图片请求，这样您觉得会更好吗？或者有更好的方案，或者其实根本没必要这么做，还望不吝赐教。TKS

**Comment by ibireme** [comment]
1. 这个没有什么太好的办法，要不然用时间换空间（图片只存原图，显示时再处理），要不然用空间换时间（按需处理，处理完都保存下来）。

2. -内存这块儿，一般都是在收到警告，或者 App 进入后台时清空内存缓存，一般来说是没什么问题的。如果你需要更详细的控制，可以看看 YYImageCache.memoryCache 里的方法，比如通过最长有效时间、最大图片数量等来做限制。
-YYWebImage 在这块儿做了处理。当 UIImageView 被释放的时候，它能通过 associated object 的释放得到通知，取消相关的图片请求。内存缓存是不会清空的，因为稍后可能还会被其他地方用到。

**Comment by lynn87** [comment]
明白你的意思，多谢回复。 (*^__^*) ……
