### ISSUE TITLE
YYImage无法加载GIF

### ISSUE THREAD

**Issue by CaiChenghan** [ibireme/YYWebImage#46]
用XIB创建的ImageView（YYAnimatedImageView），加载GIF图片无动画；而用代码创建的ImageView（YYAnimatedImageView）加载GIF图片则有动画。我在XIB创建的imageView加载图片前，调用[YYImageCache sharedCache].allowAnimatedImage = YES依旧不能展示GIF动态图。

**Comment by CaiChenghan** [comment]
不过YYImage确实强大，SDImage加载GIF图片，内存飞涨，而YYImage则没有，牛！！！

**Comment by ibireme** [comment]
xib这个应该是个已知问题，更新一下代码看看。

**Comment by ibireme** [comment]
我又实际测试了下，确实有问题。。
暂时可以在代码中设置 `imageView.autoPlayAnimatedImage = YES;` 来解决，稍后我会更新代码修复一下。

**Comment by ibireme** [comment]
Fixed

**Comment by lionner** [comment]
YYAnimatedImageView 加载 url 获取的 gif 没有动画啊，
imageView.autoPlayAnimatedImage = YES 也没有用
