### ISSUE TITLE
imageView .layer比直接用imageView加载图片快么

### ISSUE THREAD

**Issue by chengxianghe** [ibireme/YYWebImage#47]
虽然最终的实现都是_YYWebImageSetter做的处理,但是我在用的时候发现好像是imageView.layer加载图片更流畅点,我想请教的是:
1 正常使用情况下,YYWebImage更推荐那种使用方式?
2 两种方式有什么区别呢?

**Comment by ibireme** [comment]
UIImageView 显示 UIImage 时，内部处理逻辑更为复杂，它需要正确处理 UIImage 的 `imageOrientation`、`scale`、`capInsets`、`resizingMode` 等属性，如果有 `images` 或 `CIImage` 的话，它还要额外处理图片动画或滤镜。如果在某个场景下没有用到这些属性，那用 UIView.layer.contents 来显示 CGImage 是更高效的。

1. 如果没有性能问题，还是用 UIImageView 更好一些。
2. 两种方式最终都是用 layer.contents 来显示具体内容的，但 UIImageView 封装了更完善的逻辑。

**Comment by chengxianghe** [comment]
谢谢解答.

最近正在学习这个库,就流畅度上来说比SDWebImage强了不少,如果没有什么大问题,以后就可以用此库开发了.
