### ISSUE TITLE
可能的图片错误问题

### ISSUE THREAD

**Issue by yxztj** [ibireme/YYWebImage#49]
图片的Url和对应的UIImage不一致。
目前不确定是不是YYWebImage的问题，请帮忙提供一些思路。
涉及到的代码片段如下：

```objective-c
[itemView yy_setImageWithURL:[NSURL URLWithString:imageUrl] placeholder:self.defaultImage];
```

```swift
let manager = YYWebImageManager.sharedManager()
manager.requestImageWithURL(url, options: .AllowBackgroundTask, progress: nil, transform: nil, completion: {
            image, url, from, stage, error in
            completion?()
        })
```

```swift
let manager = YYWebImageManager.sharedManager()
let imageUrl = NSURL(string: urlString.encodeUrlByUTF8())
return manager.requestImageWithURL(imageUrl, options: .IgnoreImageDecoding, progress: nil,  transform: nil, completion: {
            image, url, from, stage, error in
            Async.main {
                if error == nil && image != nil {
                    successCallback(image)
                } else {
                    failCallback?(error)
                }
            }
        })
```

```swift
self.requestImageWithURL(URL, options: .AllowBackgroundTask, progress: { receivedSize, expectedSize in
            if downloadProgressBlock != nil {
                dispatch_async(callbackQueue ?? dispatch_get_main_queue(), {
                    let progress = CGFloat(receivedSize) / CGFloat(expectedSize)
                    downloadProgressBlock?(progress)
                })
            }
            }, transform: nil, completion: {
                image, url, from, stage, error in
                if error != nil {
                    dispatch_async(callbackQueue ?? dispatch_get_main_queue(), {
                        completion?(nil, error)
                    })
                    return
                }
                if stage == .Finished {
                    dispatch_async(callbackQueue ?? dispatch_get_main_queue(), {
                        completion?(image.CGImage, error)
                    })
                }
        })
```
由于调用的位置和方法都不同，而发生了同样的问题，因此我们猜测问题不是调用层造成的。
除此此外，是否可能与图片的格式有关？

**Comment by ibireme** [comment]
先排除一下缓存的问题吧：
1. 图片错乱发生后，再次设置图片时是否还是同样的错乱？如果是，那有可能是内存缓存相关问题。
2. 重启 App 后是否还是同样的错乱？如果错乱是相同的，那可能是磁盘缓存、或者使用缓存的上层问题。
3. 检查一下 App 的 Cache 文件夹内缓存内容，缓存的 key、URL 等都能直接用 SQLite 浏览工具打开看到，缓存的图片可以直接用图片浏览器打开看到，这里可以排查下磁盘缓存相关的问题。

如果缓存没有问题，那稍后再讨论下其他使用情况。

**Comment by yxztj** [comment]
我们这几天也做了大量的调试。
1. 图片错乱发生以后再次设置不一定会错乱。我们碰到过下拉刷新或者重启以后就恢复正常的，也看到过反复重启都不解决问题，只有清理Cache重新下载才能解决的。
2. 我们目前调试可以确定的是，当重启不能解决问题的时候，在YYImageCache.m的getImageForKey中下断点，key和从[_diskCache objectForKey]中返回的data生成的UIImage不匹配，也就是图片A的key却从diskCache中得到了图片B。
如果再复现重启也不能解决的问题，我们会尝试到文件系统里查看缓存内容是否正确。

**Comment by yxztj** [comment]
目前我们使用的是0.9.11的版本。我们会尝试更新到最新，但是因为复现比较困难，所以不一定能确认升级之后是否解决问题。
另外是否可以提供一些关于新版本的release notes？

**Comment by ibireme** [comment]
哦，那明白了。。
可能是这个 bug 导致的：https://github.com/ibireme/YYWebImage/commit/64815986f7a51f00883c0d487e10e2ab08445083 ，0.9.12 已修复。

稍后我会整理一下所有的项目，增加 ChangeLog。

**Comment by yxztj** [comment]
恩 之前看过这个issue，似乎是图片缓存状态导致显示失败的问题，但是因为我们遇到的问题是在不同图片之间发生的，一个image跑到了另一个地方，所以怀疑不是同一个问题。
我们会先尝试更新版本。

**Comment by ibireme** [comment]
那我整理下大概的思路吧：

1. 首先一个 URL 对应一个图片，图片内容不会有变化。
2. manager.requestImageWithURL() 这个方法的逻辑非常简单，就是用 URL 创建一个 YYWebImageOperation。其中，key 是用 url.absoluteString 生成的（如果有 cacheKeyFilter，那替换为它生成的 key）。Cache 用的是 YYImageCache 单例。除了 cacheKeyFilter 可能有问题外，这一步应该没有什么差错。
3. 一个 YYWebImageOperation 只处理一个 URL，处理完成前后会调用 YYImageCache 的方法添从缓存中取数据或者设置数据。YYImageCache 是通过 YYMemoryCache 和 YYDiskCache 访问数据的，这两个类都是用锁来保证线程安全的，这一步应该也不会导致"错乱"。
4. YYDiskCache 底层是通过 SQLite 来存储数据的，如果在这里出了问题，那数据肯定是能直接查到的。

那么。。首先检查一下是否有设置 cacheKeyFilter，再检查下出错时磁盘缓存的状态。如果有必要，把缓存的 manifest.sqlite 那三个文件、和所有缓存下来的文件名列表发一下看看。

**Comment by yxztj** [comment]
并没有设置过cacheKeyFilter。
我大致看过YYImageCache和YYMemoryCache以及YYDiskCache的实现，确实这里应该不会有并发的问题，事实上平时在生产环境或者专门测试的时候，绝大多数情况下都没有问题。
然而今天又复现了两次，而且是五张图片同时错误（每次一旦复现往往不止一张图片会出错），似乎是在某个特定情况下才能触发。将应用杀掉再重启，问题消失，说明这次diskCache并没有错。
另外，是否可以加入一些调试代码或者Log？

**Comment by ibireme** [comment]
这我也没头绪了。。

从上面描述看，调用任何方法，包括直接用 YYWebImageManager 创建 Operation，都会有可能产生图片错乱。上面的描述还有提到，有时 DiskCache 会被污染，有时 DiskCache 不会被污染但上层图片还是不对，那这只能定位到 YYWebImageOperation 和 YYImageCache 上了。晚上我又仔细查看了一遍这几个类和相关类，暂时都没发现会导致 "图片错乱" 的可能的地方。。

加调试 Log 的话，我暂时能想到这几个地方：
-  YYWebImageOperation 的 `connectionDidFinishLoading` 内，打印一下 `request`、`cacheKey` 和 `self.data.length`，确认一下用 NSURLConnection 取回的图片数据是否有问题。
- 在 YYImageCache 的 `-setImage:imageData:forKey:withType:` 内，打印一下 `imageData.length` 和 `type`，确认一下像缓存内保存时数据是否有问题。
- 在 completion block 内，打印一下 `url`, `from`, `stage`, 看看错误图片是从什么地方取回的。

**Comment by yxztj** [comment]
现在暂时还没有稳定的复现方法，因此也没有复现log。是否可以将来在代码中加入log和开关，在需要的时候可以很方便输出log。
早上又有一个用户报告问题，同样是在刚启动的时候，A处的图片（每次启动都会尝试拉取，因此应该很早就缓存过）在B处显示（B处应该是之前没有加载过的新图片）。不知道是否会cache初始化有关。

**Comment by yxztj** [comment]
看起来好像imageView.yy_setImageWithURL是想拉取一张新图片A，却获得了缓存里的另一张图片B，而B是之前就已经缓存过的。

**Comment by ibireme** [comment]
那目前从代码检查上已经找不到问题了，image cache 相关的缓存都是单例，并且都是受 dispatch_once 保护的，我们项目中目前为止也没发现类似问题。。那现在可以试着查一下上层逻辑看看，比如 URL 的传递与更新、函数调用的线程与顺序、视图对象的访问、缓存是否被其他地方调用到、图片服务器的内容是否被替换、图片 CDN 是否有未更新缓存、是否存在 URL 劫持、是否有小运营商缓存错误（比如长宽）等等。

另外，如果能拿到出错缓存的 sqlite 的那几个文件和缓存文件列表、拿到错误图片的 URL 等，也能有很好的帮助。

**Comment by yxztj** [comment]
确实不太好定位。因为实在无法稳定复现。
app外层关于CDN或者URL劫持的可能性比较低，因为出问题的用户来自各处的都有，而且安卓客户端并未遇到类似问题。我们也并未干预缓存层面的操作，只是简单调用接口查询和读取。
因为会影响生产环境而目前没有太大进展，可能先换成SDWebImage+FLAnimatedImage的方案试一段时间，看看问题是否依然存在。

**Comment by ibireme** [comment]
如果用 SDWebImage 的话，可以试试 4.0 版本：https://github.com/rs/SDWebImage/tree/4.0 已经原生集成了 FLAnimatedImage。

**Comment by yxztj** [comment]
他们4.0的branch已经半年没更新了，似乎是pending在FLAnimatedImage没有官方支持UIImage subclass。我们现在的方案是手动集成SDWebImage和FLAnimatedImage。
另外换了之后的5天暂时没有复现问题，因此图片错误问题仍然有可能在YYWebImage内部。

**Comment by ibireme** [comment]
好吧。。到头来还是没有线索。。我会继续盯着类似的问题，看看还有没有其他反馈。
