### ISSUE TITLE
help me to use it with cocospods

### ISSUE THREAD

**Issue by DexSinis** [ibireme/YYWebImage#5]
Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Finding Podfile changes
  A YYWebImage

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `YYWebImage`

**Comment by ibireme** [comment]
1. Update cocoapods to the latest version.
2. Run `pod update -verbose` and see the logs.

If the problem can not be solved, paste your logs and podfile here.

**Comment by DSKcpp** [comment]
pod 'YYWebImage', :git => 'https://github.com/ibireme/YYWebImage.git'
😄
