### ISSUE TITLE
提问：如何获取 GIF data

### ISSUE THREAD

**Issue by HebeTienCoder** [ibireme/YYWebImage#50]
用YYWebImage下载来的图片，是gif，想分享到微信QQ，需要NSData，请问如何通过YYWebManager获取到呀？

**Comment by ibireme** [comment]
NSData *data = nil;
    if ([image isKindOfClass:[YYImage class]]) {
        data = ((YYImage *)image).animatedImageData;
    }
    if (!data) {
        YYWebImageManager *manager = [YYWebImageManager sharedManager];
        NSString *key = [manager cacheKeyForURL:url];
        data = [manager.cache getImageDataForKey:key];
    }
    
    return data;

**Comment by HebeTienCoder** [comment]
哦哦  谢啦

**Comment by HebeTienCoder** [comment]
下载图片的时候，刚刚下载完成就取data数据
经常会出现取不到data数据的情况  为nil
但是image有值。。

**Comment by ibireme** [comment]
那应该是磁盘缓存还未写完成。。

如果图片是 GIF、APNG、WebP 动图的话，`((YYImage *)image).animatedImageData` 这块儿应该就能取到 data 了，如果去不到，那就直接用 UIImageJPEGRepresentation() 之类的方法来生成数据吧。

**Comment by HebeTienCoder** [comment]
现在时另外一个需求，有可能是jpg。。我刚才看了您的源码，确实是磁盘没有写完成，下下来的图片6K，用UIImageJPEGRepresentation生成的有13K。。。。

**Comment by ibireme** [comment]
如果非得要立刻获取下载回来的原始数据，那可能要改一下代码了。。

比如在 YYImageCache 里在加一个临时的 memoryCache，专门保存那些刚放入 DiskCache 的数据，然后再保存成功后再删除。

**Comment by HebeTienCoder** [comment]
嗯嗯，我改好了，谢谢知道，哈哈

**Comment by CaiChenghan** [comment]
怎么获取GIF图片的所有帧图片？

**Comment by ibireme** [comment]
YYImage 实现了 <YYAnimatedImage> 协议，通过这个协议可以获取所有帧图片等数据：https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/Image/YYAnimatedImageView.h#L95-L121

**Comment by CaiChenghan** [comment]
终于看到了，谢谢大哥。不过我还有个问题，怎么控制GIF图片只播放一次呢？

**Comment by ibireme** [comment]
GIF 的播放次数是 GIF 图片本身的属性，这应该是只读的。想要控制循环次数，大概有几种方法：

1.如果你不能控制 GIF 图片内容，那你可以监听 YYAnimatedImageView 的 currentAnimatedImageIndex 属性，当播放到最后一帧时，调用 stopAnimating 停止动画。
2.子类化 YYImage，把循环次数这个属性暴露出来：https://github.com/ibireme/YYImage/issues/1
3.用比较 hack 的方法来做：

    if ([image isKindOfClass:[YYImage class]]) {
        YYImageDecoder *decoder = [image valueForKey:@"_decoder"];
        [decoder setValue:@(1) forKey:@"loopCount"];
    }
