### ISSUE TITLE
对于gif图的转换问题

### ISSUE THREAD

**Issue by GabrielOmarBatistuta** [ibireme/YYWebImage#52]
下载下的gif图片,是从NSData转换的 有无方法转换回去?暴露出来的下载完成回调里都没有提供NSData

**Comment by GabrielOmarBatistuta** [comment]
我现在的做法是通过找到缓存的path,然后用NSData提供的方法转换的.

**Comment by ibireme** [comment]
可以参考这个问题：https://github.com/ibireme/YYWebImage/issues/50

**Comment by GabrielOmarBatistuta** [comment]
非常感谢~正是我要的
