### ISSUE TITLE
YYWebImageOptionProgressiveBlur not work

### ISSUE THREAD

**Issue by shiqyn** [ibireme/YYWebImage#57]
Thanks for your great open resource.

In YYWebImageExample, why load some jpg has YYWebImageOptionProgressiveBlur effect, but load other jpg YYWebImageOptionProgressiveBlur not work, like "https://d13yacurqjgara.cloudfront.net/users/26059/screenshots/2047158/beerhenge.jpg".

**Comment by ibireme** [comment]
It's not a `progressive` JPEG file.

When encode an image (save the image to file), you may choice the image progressive option:
JPEG support `baseline` and `progressive` option,
PNG support `baseline` and `interlaced` option,
GIF support `baseline` and `interlaced` option.

`YYWebImageOptionProgressive` support all these options,
`YYWebImageOptionProgressiveBlur` only support `interlaced` and `progressive` image.

See: https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYWebImageManager.h#L29-L34

---

![image_baseline](https://cloud.githubusercontent.com/assets/839283/13164494/b0416662-d6f0-11e5-8732-3b0ae32ae397.gif)
baseline

![image_interlaced](https://cloud.githubusercontent.com/assets/839283/13164496/b45e5dc2-d6f0-11e5-8bc7-5d7d76d00933.gif)
interlaced

![image_progressive](https://cloud.githubusercontent.com/assets/839283/13164497/b70fceac-d6f0-11e5-8e32-02b02c9e83a1.gif)
progressive

**Comment by shiqyn** [comment]
I see. Thanks for your reply.
