### ISSUE TITLE
关于图片切圆角的问题

### ISSUE THREAD

**Issue by PrideChung** [ibireme/YYWebImage#58]
iOS 7以后`UIBezierPath`切圆角的方法其实是有很大问题的，感觉这个问题介于bug和feature之间，具体请看PaintCode这篇文章
http://www.paintcodeapp.com/news/code-for-ios-7-rounded-rectangles

在用`yy_imageByRoundCornerRadius`切圆角图片的时候我就碰到了这个问题，30x30的图片，cornerRadius用12居然切成了正圆。本来是在把使用`CALayer`的cornerRadius属性的方法改成圆角图片，但是似乎是没法获得想要的效果，只要cornerRadius大于正方形边长的1/3，图片就会突然变成正圆。

**Comment by ibireme** [comment]
是的，那个方法出来的 Path，有些像桌面图标，圆角与直线之间的连接显得更自然一些。

一般给图片加圆角，radius 的值是比较小的，这样不会产生太大误差，效果也比原来的正圆弧的更圆润。

我更倾向于把这看作是 feature，但有可能不符合某些人预期。这可以加一些注释说明，或者额外加一个参数。

**Comment by PrideChung** [comment]
PS，
```
- (UIImage *)imageByRoundCornerRadius:(CGFloat)radius
                                 corners:(UIRectCorner)corners
                             borderWidth:(CGFloat)borderWidth
                             borderColor:(UIColor *)borderColor
                          borderLineJoin:(CGLineJoin)borderLineJoin;
```
这个方法如果提供了UIRectCorner参数，画出来的圆角是上下左右颠倒的，应该是因为这两行代码的缘故
```
 CGContextScaleCTM(context, 1, -1);
 CGContextTranslateCTM(context, 0, -rect.size.height);
```

**Comment by ibireme** [comment]
嗯哈。。这应该是 bug 了。

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYWebImage/commit/919a4df8e7e281bb5df63a9b166389377832c79f

**Comment by Phelthas** [comment]
请教点问题：
`- (UIImage *)imageByRoundCornerRadius:(CGFloat)radius
                                 corners:(UIRectCorner)corners
                             borderWidth:(CGFloat)borderWidth
                             borderColor:(UIColor *)borderColor
                          borderLineJoin:(CGLineJoin)borderLineJoin;`  
这个方法里面用了`CGContextDrawImage(context, rect, self.CGImage)`的方法，所以要加
```
CGContextScaleCTM(context, 1, -1);        
CGContextTranslateCTM(context, 0, -rect.size.height); 
```
来修正坐标系的问题，所以UIRectCorner的方向如果不处理的话也是颠倒的；    
为什么不直接用`[self drawInRect:rect]`呢？这个方法不是自动处理了坐标系的问题吗，用这个方法就不用加那两句代码，也不用特殊处理UIRectCorner了吧？还是说这里有什么其他考虑？    

另外，下面设置边框那一段
```
CGFloat strokeInset = (floor(borderWidth * self.scale) + 0.5) / self.scale;
CGRect strokeRect = CGRectInset(rect, strokeInset, strokeInset);
CGFloat strokeRadius = radius > self.scale / 2.0 ? radius - self.scale / 2.0 : 0;
```
这几句没看懂什么意思啊，为什么要这么处理呢？能否给讲解下?
测试的时候图片边框距离最边缘有一点点的空隙，貌似也是这几句造成的
