### ISSUE TITLE
YYImageDecoder 发生严重的内存疯长问题

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYWebImage#59]
请看以下截图：
![screen shot 2016-02-25 at 00 32 03](https://cloud.githubusercontent.com/assets/5517281/13292574/3ff2c188-db57-11e5-8fdc-276e801c30b7.png)

**Comment by KittenYang** [comment]
调用代码如下：
```objc
imageView.layer.yy_setImageWithURL(NSURL(string: bmiddleUrl), placeholder: WBStatusHelper.imageNamed("placeholder_image"), options: .SetImageWithFadeAnimation, completion: { (image, url, imageFromType, imageStage, error) -> Void in
    
    if image != nil && image.size.width > 0 && (image.size.height / image.size.width) > 3 {
        imageView.badgeTagView.hidden = false
        imageView.badgeTagView.layer.contents = WBStatusHelper.imageNamed("image_type_longpic").CGImage
    }
    print("Image loaded!")
})
```

**Comment by ibireme** [comment]
这里这个方法，是 CoreGraphic 的，用于把图片解码到内存。解码后的图片数据，会关联到 UIImage 里，随后会 UIImage 缓存到 YYMemoryCache 内。默认配置下，如果设备内存足够，那 MemoryCache 里会尽可能多的缓存数据，直到收到内存警告或应用退到后台。

这可以让 App 退到后台，或者给 App 发送个内存警告，再看看内存是否会被释放掉。这里可以修改一下 MemoryCache 的配置来调整内存缓存策略。

**Comment by KittenYang** [comment]
而且我同时发现 YYKitDemo 里的微博 Timeline 也出现类似内存疯涨的问题，怀疑可能是 image decode 出了问题。因为注释掉 setImageWithURL 方法内存疯涨问题解决。

**Comment by KittenYang** [comment]
原来如此，明白了。感谢解答（其实是没有仔细看源码orz）。

**Comment by KittenYang** [comment]
@ibireme  其实还有个疑问，为什么一定要缓存到内存里，不可以缓存到 disk 吗？

**Comment by ibireme** [comment]
内存缓存基本都是这个逻辑啊，比如 SDWebImage 内部是用的 NSCache，在默认配置情况下，也是尽可能多的缓存数据。和 PC 设备不一样，移动设备里，同一时间只有一个 App 在前台，那设备有足够内存时，如果不用的话反而是浪费。

内存缓存的好处是完全没有性能问题，如果图片已经在内存里，那显示时不会有任何延迟。磁盘缓存这里 也有，但相对于内存缓存来说，磁盘缓存的性能还是差太多了：它要占用磁盘 I/O 来读取文件，还要占用很多的 CPU 资源来解码图片数据。

可能不同 App 也有不同的缓存策略，MemoryCache 和 DiskCache 在这里也有提供接口来控制最大数量和最大空间限制。

**Comment by KittenYang** [comment]
@ibireme 今天仔细看了一边 YYImage 的源码，加上您这一番解释，解惑了以往许多误解，非常感谢您的解答，要向您学的还有很多！
