### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by Sunnyyoung** [ibireme/YYWebImage#6]
![image](https://cloud.githubusercontent.com/assets/5926284/11084408/b9add0ba-8875-11e5-9818-c126466ff7ec.png)

如图，该库会有内存泄漏问题，望修复，thx~

**Comment by ibireme** [comment]
感谢提出问题！
已修复，请更新代码或 pod 验证一下。

**Comment by Sunnyyoung** [comment]
@ibireme 👍

**Comment by conscientiousness** [comment]
@ibireme thanks a lot!!
