### ISSUE TITLE
YYAnimationView在CollectView中的问题

### ISSUE THREAD

**Issue by HotWordland** [ibireme/YYWebImage#60]
感谢开源
我将animationView集成到CollectViewCell中滑动和显示都非常正常,但是每当我delete掉一个cell,而后出现的cell中animationView明显播放帧率下降了,大概每隔2-3秒才播放一帧,必须要重新滑动后才能恢复正常.在数据源代理中调用startAnimating也不起作用.

**Comment by ibireme** [comment]
不清楚具体情况，只能猜测几种可能：

1. 之前 YYImage 有个问题会导致某些情况下，设备内存低时的消耗一些多余的 CPU 资源。你可以临时用当前 Master 下最新的代码试试看，看能否能解决问题。
2. 看一下 CPU 占用，如果 CPU 占用高，那可能是图片太大、或者可能是其他资源占用了 CPU。
3. 看一下 imageView.runloopMode 的值是否是 NSRunLoopCommonModes，如果不是该值哪应该重新设置一下。
4. 用 Instruments 看一下 GPU 占用，如果 GPU 太高，那可能是界面显示了太多图片。

**Comment by HotWordland** [comment]
恩 谢谢
