### ISSUE TITLE
可以支持为placeholder设置不同的缩放模式吗？

### ISSUE THREAD

**Issue by xilin** [ibireme/YYWebImage#61]
placeholder可能是个小图，不缩放；加载的图片是个大图，需要特定的缩放模式。

**Comment by ibireme** [comment]
缩放，是 UIViewContentMode 吗？

    __weak typeof(imageView) weakImageView = imageView;
    
    imageView.contentMode = UIViewContentModeCenter;
    [imageView yy_setImageWithURL:url
                      placeholder:placeholder
                          options:kNilOptions
                       completion:^(UIImage *image, NSURL *url, YYWebImageFromType from, YYWebImageStage stage, NSError *error){
                           if (stage == YYWebImageStageFinished) {
                               weakImageView.contentMode = UIViewContentModeScaleAspectFill;
                           }
                       }];

**Comment by xilin** [comment]
是的，是UIViewContentMode。我现在就是在completion block里做的。不过感觉不够优雅，每次使用时都要设置一下变化。我自己做一下封装吧~

不过这样做的时候还有一个问题，重用UITableViewCell时，imageView的UIViewContentMode好像会被记住，即使我在prepareForReuse中重设成UIViewContentModeCenter了，也会显示成UIViewContentModeScaleAspectFill的placeholder样式。

**Comment by ibireme** [comment]
没必要在 prepareForReuse 里设置 contentMode。

每次调用 setImageWithURL 前，设置一下 contentMode，然后在 completion block 里，再判断一下 image 是否不为空。

**Comment by xilin** [comment]
好的，我再试试看
