### ISSUE TITLE
关于下载大图片造成图片花屏的请教

### ISSUE THREAD

**Issue by JustTian** [ibireme/YYWebImage#62]
我在使用SDWebimage的时候会偶尔出现图片花屏的现象，但是使用YYWebImage到现在没出现过，请问你是采用了什么方式来检测吗？

**Comment by ibireme** [comment]
如果 SDWebimage 对某一张特定的图片花屏，并且能一直复现，那可以用那张图片来检测一下。。

SDWebImage 经过长时间的维护而且使用广泛，应该不太容易出问题。所以说我不太确定是库本身的问题，还是网络或者其他原因导致的。这两个库在解码图片时，有一些不一样的地方：[YYImageCoder.m#L875~L892](https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/Image/YYImageCoder.m#L875-L892)  、  [SDWebImageDecoder.m##L28-L65 ](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDecoder.m#L28-L65) 如果真是由于库本身导致的，我猜，有可能会出现在这个地方。

**Comment by JustTian** [comment]
非常感谢你的解答，最后发现是文件服务器返回文件问题，但是我有一个疑惑，为啥我只有在快速滑动我的加载图片列表才有可能出现花屏；难道说是异步下载图片时候滑动图片对文件下载会有影响?

**Comment by ibireme** [comment]
这就不清楚了。。
