### ISSUE TITLE
WebP.framework 引起编译不通过

### ISSUE THREAD

**Issue by acBool** [ibireme/YYWebImage#63]
如果工程中不加 WebP.framework,则会报类似于 "_WebPConfigInitLnternal"，referenced from:  的错误。
如果加上 WebP.framework，ios9 下会报 "** dumplcate symbols for architecture x86_64" 的错误,iOS7 下可以编译通过。

**Comment by acBool** [comment]
冲突的文件是 lossless_enc.o
貌似是和 SDWebImage 冲突了。有什么解决办法嘛？

**Comment by ibireme** [comment]
SDWebImage 带的 libwebp 是用默认配置编译的，不包含 demux 模块，所以无法解码 WebP 动图，但是它却会把 demux.h 头文件引入进来，这就导致了 YYWebImage 编译不过。
YYWebImage 带的 WebP.framework 是用一个[自定义脚本](https://github.com/ibireme/YYWebImage/blob/master/Vendor/WebP.sh)编译的，包含了 demux 模块。

如果你是用 CocoaPods 管理的库，那 `'YYImage/WebP'` 和 `'SDWebImage/WebP'` 只能保留一个，这样 YY 和 SD 也只有其中一个能解码 WebP 格式。

如果你是手动管理的，那可以尝试把 SDWebImage 带的 libwebp 移除，然后让两边都依赖 WebP.framework，这样也能解决冲突。

另外，如果项目编译选项里有 -all_load，那可以先去掉看看。
