### ISSUE TITLE
最新YYWebImage库用CocoaPods导入，模拟器运行编译不通过了。真机可以。

### ISSUE THREAD

**Issue by pandaBilbo** [ibireme/YYWebImage#64]
https://github.com/ibireme/YYWebImage/issues/56

**Comment by ibireme** [comment]
我测试了一下：Xcode 7.2 新建工程，CocoaPods 0.39.0，Podfile 里仅引用了 YYWebImage 1.0，use_frameworks! 开启和关闭状态都测试了一遍，模拟器和真机编译都没问题。

不清楚具体的错误原因。

**Comment by pandaBilbo** [comment]
podfile里面没有加use_frameworks!，加了就好了
