### ISSUE TITLE
如果图片正在下载，是否可以返回当前状态？

### ISSUE THREAD

**Issue by speedpursuer** [ibireme/YYWebImage#66]
您好，

正如YYWebImageExample中的例子，如果在前面的图片还没有下载完成时，用户滚动到下面，再回到上面，前面正在下载的图片又会重新下载，而不是返回下载中的状态继续，导致重复下载。

对于这种情况（利用UITableView减少内存使用），又希望所有正在下载的图片都保持下载完成（或显示失败），有什么好的办法？

多谢指点！

**Comment by ibireme** [comment]
Cell 是复用的，所以当 Cell 被回收并显示新的操作时，那 Cell 原先的操作自然是会被取消的。

如果你希望自己管理下载状态，那应该在 TableView 外，用 WebImageManager 和 WebImageOperation 来统一管理下载策略。你可能需要一个单独的 YYWebImageManager 并且控制总并发数量，并且在新请求出现时及时取消可能不在需要的旧请求（例如用 LRU）。即使这么做，得到的好处也不会太多。。

**Comment by speedpursuer** [comment]
谢谢您的回复！非常清晰有帮助！

的确，换来的好处也就更好一些的用户体验，和非Tabelview、固定数据长度的场景一样能够自动完成视线以外已开始下载。

这个不是issue，您关闭它吧。

再次感谢！

**Comment by speedpursuer** [comment]
您好，

不好意思，之前表述有些问题，想在此进一步询问下。

比如用方法yy_setImageWithURL开始一个图片下载。在它仍继续下载并没有完成前，如果再次调用yy_setImageWithURL，这样它会停止当前的operation重新开始一次新的下载。

我的问题是：是否可以在再次调用yy_setImageWithURL时判断此图片正在下载，如果是继续下载并返回下载状态呢？或者已有类似的机制（不同于yy_setImageWithURL的方法）？

谢谢您的帮助！

**Comment by ibireme** [comment]
一般情况下（没有用 placeholder/progressive），可以直接取一下 imageView.image 看看，nil 就是还没下完。

如果要获取到完整的下载情况，那可以在 progress 和 completion block 里监听事件，并把状态传递到外面。

**Comment by speedpursuer** [comment]
之前是想这样的逻辑是否可以封装在库内部统一管理。根据您的建议（方法2，因为使用了placeholder），在外部自己实现。可能您考虑这样的设计更加自由灵活。

再次感谢！

**Comment by ibireme** [comment]
由于图像显示这块儿，性能非常敏感，稍微有多余的主线程操作就会影响到 UI 的流畅性。所以最开始做的时候，那些不常用的属性是没有封装的。。

这个以后有空可以试着加一下。
