### ISSUE TITLE
setImageWithURL newImage

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYWebImage#67]
[tempView setImageWithURL:[NSURL URLWithString:[Preference sharedInstance].currentUser.avatar] placeholder:Image(@"login_icon_phone") options:YYWebImageOptionSetImageWithFadeAnimation progress:^(NSInteger receivedSize, NSInteger expectedSize) {

    } transform:^UIImage *(UIImage *image, NSURL *url) {
        NSLog(@"%@-",url);
        UIImage *newImage = [UIImage imageWithCGImage:image.CGImage scale:1 orientation:UIImageOrientationDown];
        return newImage;
    } completion:^(UIImage *image, NSURL *url, YYWebImageFromType from, YYWebImageStage stage, NSError *error) {

    }];

如果说我有2个地方用到了同一个图（URL）。，但是2个图加载方式不一样。一个可能是要旋转的。但是我发现2个地方的图片始终都是旋转的。

**Comment by ibireme** [comment]
transform 是针对 URL 的，transform 后的图片会被缓存下来。

`imageWithCGImage:scale:orientation:` 这个方法，并没有什么性能消耗，所以推荐放到 completion block 里。

另外也可以自己创建单独的 ImageManager 来单独管理。

**Comment by 597579501** [comment]
@ibireme 主要我是想直接将URL得来的图片按不同指定的方式加载到imageView上。如你第一个方法。

**Comment by 597579501** [comment]
@ibireme 
completion:^(UIImage *image, NSURL *url, YYWebImageFromType from, YYWebImageStage stage, NSError *error) {
        UIImage *newImage = [UIImage imageWithCGImage:image.CGImage scale:1 orientation:UIImageOrientationLeft];
        [tempView setImage:newImage];
    }];
这样？

**Comment by ibireme** [comment]
对的。。

transform 是假定调用者会对每个 URL 的图片执行相同操作。transform 内有可能会进行一些非常消耗资源的操作，返回一个完全不同的图片，所以这里是要缓存下来保证下次再用时不会重复执行那些操作。
