### ISSUE TITLE
YYWebImage 如何获取磁盘上图片的缓存路径？

### ISSUE THREAD

**Issue by acBool** [ibireme/YYWebImage#68]
下载下来的图片想分享微信，SDWebImage有这样的方法  [[SDImageCache sharedImageCache] defaultCachePathForKey:urlAsString];   ，获取到图片在本地的path，然后得到图片的data，然后可以进行分享。YYWebImage有没有类似的方法呢？

**Comment by ibireme** [comment]
YYWebImageManager *manager = [YYWebImageManager sharedManager];
    NSString *cacheKey = [manager cacheKeyForURL:url];
    NSData *data = (id)[manager.cache.diskCache objectForKey:cacheKey];

体积小的图片有可能会保存到 SQLite 里，所以这里没有获取 path 的接口。
