### ISSUE TITLE
使用pod更新YYWeImage后提示 file not found .

### ISSUE THREAD

**Issue by jinxiansen** [ibireme/YYWebImage#69]
-

**Comment by ibireme** [comment]
没有更多信息。

这是哪里的提示？如果是 CocoaPods 给的提示，那应该检查 CocoaPods。

**Comment by xilin** [comment]
有可能是你网络状况不好没有下全
试试清空后重下
rm -rf ~/Library/Caches/CocoaPods/
rm -rf "`pwd`/Pods/"
pod install --verbose
用verbose mode查看下提示

**Comment by jinxiansen** [comment]
是Xcode 的提示。 这不能上截图呢。 非常感谢xilin ，下次遇到试试。昨日手动导入YYWebImage，并注掉了 头文件中尖括号包含的 if ...end。正常编译了。

**Comment by ibireme** [comment]
图片可以在评论框内拖拽上传。

**Comment by CYXiang** [comment]
@jinxiansen 可能是网络问题，试试离线更新
