### ISSUE TITLE
有没有类似这种用法downloadImageWithURL

### ISSUE THREAD

**Issue by conscientiousness** [ibireme/YYWebImage#7]
请问大神有没有类似这种用法,謝謝？
```
SDWebImageManager *manager = [SDWebImageManager sharedManager];
[manager downloadImageWithURL:imageURL
                      options:0
                     progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                         // progression tracking code
                     }
                     completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
                         if (image) {
                             // do something with image
                         }
                     }];
```

**Comment by ibireme** [comment]
代码类似：

    YYWebImageManager *manager = [YYWebImageManager sharedManager];
    [manager requestImageWithURL:url
        options:kNilOptions
        progress:^(NSInteger receivedSize, NSInteger expectedSize) {
            // progression tracking code
        }
        transform:nil
        completion:^(UIImage *image, NSURL *url, YYWebImageFromType from, YYWebImageStage stage, NSError *error){
            if (image) {
                // do something with image
            }
        }];

**Comment by conscientiousness** [comment]
@ibireme 感谢理解了，另一问我要如何取用cache呢?

**Comment by ibireme** [comment]
举个例子

    YYWebImageManager *manager = [YYWebImageManager sharedManager];
    YYImageCache *cache = manager.cache;
    UIImage *image = [cache getImageForKey:[manager cacheKeyForURL:url] withType:YYImageCacheTypeMemory];
    
    YYMemoryCache *memoryCache = cache.memoryCache;
    YYDiskCache *diskCache = cache.diskCache;

**Comment by conscientiousness** [comment]
@ibireme thanks a lot!!
