### ISSUE TITLE
YYWebImage 能否取消下载呢？

### ISSUE THREAD

**Issue by acBool** [ibireme/YYWebImage#70]
问题是这样：使用UITableView或者UICollectionView时，使用 YYWebImage 加载图片，虽然是异步，但是快速滑动时，有些图片没来得及加载，但是在后台实际上还在加载。
因此问一下，YYWebImage 有没有取消下载的操作呢？类似于SDWebImage 的 cancellAll 操作？

**Comment by ibireme** [comment]
[imageView yy_cancelCurrentImageRequest];
    [[YYWebImageManager sharedManager].queue cancelAllOperations];
