### ISSUE TITLE
下载1080*1920图片，得到的却是540*960的图片

### ISSUE THREAD

**Issue by lieyunye** [ibireme/YYWebImage#71]
为什么这么处理呢

YYWebImageManager *manager = [[YYWebImageManager alloc] initWithCache:[self createImageCache] queue:[YYWebImageManager sharedManager].queue];
                [manager requestImageWithURL:[NSURL URLWithString:[response objectForKey:@"url"]] options:YYWebImageOptionRefreshImageCache progress:nil transform:nil completion:^(UIImage * _Nullable image, NSURL * _Nonnull url, YYWebImageFromType from, YYWebImageStage stage, NSError * _Nullable error) {
                }];

**Comment by ibireme** [comment]
UIImage 创建时用的是 UIScreen 的 scale。如果想要获取图像的实际像素大小，用 image.CGImage 来获取。

好处是图像显示时能与屏幕像素对齐。

**Comment by lieyunye** [comment]
那怎么得到原图啊
