### ISSUE TITLE
请教关于内存泄漏的问题

### ISSUE THREAD

**Issue by speedpursuer** [ibireme/YYWebImage#72]
您好，

不好意思，又打扰了。

我在测试YYWebImageExample时发现类似“内存泄露”的问题：如果创建大量的图片，并反复对YYWebImageExample进行pushViewController和返回（我修改了程序让每次push后下载和显示不同的图片）。这样内存使用量会快速上升。

我尝试在viewDidDisappear中调用[[YYImageCache sharedCache].memoryCache removeAllObjects]释放内存，“返回”后内存是降下来了，但是还不是完全释放。而且，随着不断多次的push、返回再push这样下去（即下载大量的图片之后），内存的使用量就非常可观了。

我在viewDidDisappear中还将所有visibleCells的webImageView设为nil，也没有效果。

请问这种情况内存是被消耗在哪里呢？是否有办法在离开显示图片的viewCtr尽量释放全部内存？我的应用场景需要显示大量图片，内存的有效控制比读取速度更重要（从磁盘读取的速度完全够）。

谢谢！

**Comment by ibireme** [comment]
<img width="843" alt="2016-03-16 9 14 15" src="https://cloud.githubusercontent.com/assets/839283/13813367/1c3ee6e8-ebbc-11e5-878c-1e9673bbd5b5.png">
这是我杠杆在 iPhone6 真机上的测试结果，频繁 push 和 pop、reload 等操作，内存并没有上涨。另外，你也可以看看 YYKitDemo 那个项目，那里面的微博 Demo 同样也显示了大量不同的图片，内存也是可控的。

`修改了程序让每次push后下载和显示不同的图片` 具体是什么样的逻辑？如果能提供一个可复现的 Demo 那我可以仔细查一下。

**Comment by speedpursuer** [comment]
多谢您的快速回复！我去参考一下您说的YYKitDemo，自己排查一下是否是我代码的问题。如有进一步发现需要您帮忙，我来提供一个Demo。
谢谢指点！

**Comment by speedpursuer** [comment]
顺便请教一下：pop之后，这个调用是否需要呢？
[[YYImageCache sharedCache].memoryCache removeAllObjects]
谢谢！

**Comment by ibireme** [comment]
不需要。
默认这个内存会在遇到内存警告或者App退到后台时自动清空。另外你也可以手动调节一下它的 countLimit、costLimit。

**Comment by speedpursuer** [comment]
我找到了原因，确实是我修改的代码导致了内存泄露。

我在YYWebImageExampleCell中增加了一个属性或者变量用来记录cell图片的下载状态，例如：
@property (nonatomic, strong) BOOL *downloaded;
然后在下载completion中设置：if(!error) downloaded = true;

就是这个属性导致了问题。可是还没想明白原因，望指点！

谢谢！

**Comment by ibireme** [comment]
有可能是循环引用了。

**Comment by speedpursuer** [comment]
确实是循环引用了。
问题解决后反复测试，没有任何内存问题了，谢谢！！
