### ISSUE TITLE
使用yy_imageUrl报错

### ISSUE THREAD

**Issue by TonyXuChen** [ibireme/YYWebImage#73]
用YYAnimatedImageView声明iv，iv.yy_imageURL = url会报错：[UIImageView setYy_imageURL:]: unrecognized selector sent to instance 0x138015330

**Comment by ibireme** [comment]
这是没有编译 YYWebImage？
YYWebImage 是有这个方法的：https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/Categories/UIImageView%2BYYWebImage.m#L34

**Comment by TonyXuChen** [comment]
编译都通过了，只不过运行的时候一到这个方法直接就报错了，就像运行的时候imageview没有这个方法一样

**Comment by TonyXuChen** [comment]
难道是没有在other linker flags里面添加么

**Comment by ibireme** [comment]
你。。是怎么安装的？

**Comment by TonyXuChen** [comment]
我找到问题了，是因为我的build phase里面没有引用的问题，但是我不知道为什么我写的demo没有引用这一步也能正常显示，不过现在应该是解决了，麻烦你了。

Date: Mon, 21 Mar 2016 06:30:32 -0700

**Comment by TonyXuChen** [comment]
现在能正常使用框架，但是出现了一个关于webp的问题。第一，解析webp的gif的时候总会消耗大量的cpu，虽然cpu过一段时间不滑动列表会降下来。第二，我在上拉加载更多数据的时候，CPU很容易就爆满了然后webp的gif显示就会一卡一卡的，并且这种cpu一直都会居高不下，只有离开这个页面才会降下来，但是返回这个页面又会升到很高。有没有不在tableview显示范围内停止解析webp的机制呢？

**Comment by ibireme** [comment]
WebP 和 GIF 是两种格式。

解码动图时，肯定是消耗 CPU 的，如果图片太大太复杂、帧数太多、手机 CPU 性能来不及边解码边显示，那动图的动画就会卡顿，但这不会阻塞主线程。如果一次性全部解码到内存，那内存会承受不了的。

如果想禁用动图格式，那可以用 UIImageView 来显示就行。

另外，有关 YYImage 的文档，可以看这里：https://github.com/ibireme/YYImage#animation-control

**Comment by TonyXuChen** [comment]
当我用自己的工程的列表显示GIF的时候，很顺利并且CPU占用很低，但是当我转而显示webp类型的GIF的时候（这些WEBP都是由我前面说的GIF转来的），主线程的确不阻塞，但是好像不断滚动刷新的时候CPU不断增加，然后即使后来停下来放在那里不动，CPU也不降下来了

**Comment by ibireme** [comment]
WebP 的解码比 GIF 的解码要消耗更多的 CPU 资源，另外 YYAnimatedImageView 会在内存足够时尝试缓存一些帧数据到内存。你可以手动设置一下 imageView. maxBufferSize 来手动指定缓存大小。

**Comment by TonyXuChen** [comment]
现在解析webp的感觉就是一个tableview里面的所有webp都在解析，就算全部解析显示出来了之后还在消耗cpu的样子，我看了下有些线程一直在占用CPU,即使都已经播放了很久
![88c968d6-08d7-4f7b-8c56-77e22b2dff6b](https://cloud.githubusercontent.com/assets/8279925/13946845/0c345c3e-f052-11e5-8e5e-b1dd1f7adeed.png)

**Comment by ibireme** [comment]
这个动图是边播放边解码的啊，内存不够没有缓存时，当然是一直在解码了。。
类似用播放器放视频的逻辑。

**Comment by TonyXuChen** [comment]
但是只要是我滑动tableview显示到的webp动图全都在解码，就算已经滑动到屏幕外看不见了还是这样，并且上图看来memory应该还是有很多空间啊。我用你的demo播放的时候，滑动到webp的时候cpu会升高，但是当解析完了之后他的cpu就会降下去。我用自己的工程就不行，但是自己的工程解析GIF格式动图的时候就没有这个问题

**Comment by ibireme** [comment]
是否缓存、缓存多少等取决于具体设备和图片显示时的设备状态、图片本身的大小、帧数等条件，具体逻辑见这里：https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/Image/YYAnimatedImageView.m#L381-L394

另外，解码 GIF 和 解码 WebP 的逻辑也完全不一样。

**Comment by TonyXuChen** [comment]
当同时解码多张webp动图的时候，由于cpu占用过大，会占用了其他操作比如网络请求的cpu，会使网络请求变得很慢，这种情况有没有什么应对的办法呢？

**Comment by ibireme** [comment]
网络请求不占用过多 CPU，图片解码也是用的 GCD 的异步操作，所以我觉得网络慢与图片解码没关系。

另外， WebP 动图确实要消耗更多 CPU 解码，如果觉得不能接受那就换成 GIF 或 APNG 呗。

**Comment by TonyXuChen** [comment]
能不能给YYWebImageManager 的requestImageWithURL方法更改一下，让返回的是YYImage的对象，不然动图并不能通过completion的block来获得。

**Comment by ibireme** [comment]
返回的图片不一定是 YYImage，还可能是普通的 UIImage，因为 YYImage 是 UIImage 的子类，所以这里肯定不能标示为 YYImage。这里可以直接判断 class。

如果图片是 nil，那可以打印一下 error 信息，一般都是网络错误。
