### ISSUE TITLE
使用YYWebImage加载图片完成后，退到后台再回来刷新一下页面图片重新load时图片会闪一下

### ISSUE THREAD

**Issue by zyi1992** [ibireme/YYWebImage#75]
如题，正常的使用会出现这种问题，个人考虑到应该是退到后台，memory cache 被清除了，再次加载时，memory cache里找不到图片，这个时候图片里的内容换成了placeholder，之后又有一些操作导致后面从disk cache里加载出来图片有一定延时，从而导致图片出现一定的空白期 我个人的改法是 
NSString *key = [[YYWebImageManager sharedManager] cacheKeyForURL:[NSURL URLWithString:url]];
    UIImage *lastPreviousCachedImage = [[YYWebImageManager sharedManager].cache getImageForKey:key];
    [self yy_setImageWithURL:[NSURL URLWithString:url] placeholder:lastPreviousCachedImage?lastPreviousCachedImage:placeholder options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
    } transform:^UIImage * _Nullable(UIImage * _Nonnull image, NSURL * _Nonnull url) {
        return image;
    } completion:^(UIImage * _Nullable image, NSURL * _Nonnull url, YYWebImageFromType from, YYWebImageStage stage, NSError * _Nullable error) {
        if (completed) {
            completed(image,error,url,NO);
        }
    }];
这个也是SDWebImage里的一种做法  ，这个会解决闪的问题，但是我的疑问是为什么不能直接用disk cache里的图片  比如这样
NSString *key = [[YYWebImageManager sharedManager] cacheKeyForURL:[NSURL URLWithString:url]];
    UIImage *lastPreviousCachedImage = [[YYWebImageManager sharedManager].cache getImageForKey:key];
    if(lastPreviousCachedImage){
        self.image = lastPreviousCachedImage;
    }else {
        [self yy_setImageWithURL:[NSURL URLWithString:url] placeholder:placeholder options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        } transform:^UIImage * _Nullable(UIImage * _Nonnull image, NSURL * _Nonnull url) {
            return image;
        } completion:^(UIImage * _Nullable image, NSURL * _Nonnull url, YYWebImageFromType from, YYWebImageStage stage, NSError * _Nullable error) {
            if (completed) {
                completed(image,error,url,NO);
            }
        }];
    }
这样操作会有什么问题吗，个人的理解可能有些肤浅，希望得到你的回复？

**Comment by ibireme** [comment]
从磁盘读取文件是非常耗时的操作，如果放到主线程会造成卡顿。。

不论如何，缓存总是有可能失效的，所以总有可能会出现空白。。可以用 `YYWebImageOptionSetImageWithFadeAnimation` 为这个过程加一个很短的渐变，看着可能会好一些。

**Comment by zyi1992** [comment]
我看到YYWebImage里从磁盘读图片是在这个位置
` dispatch_async([self.class _imageQueue], ^{
                    __strong typeof(_self) self = _self;
                    if (!self || [self isCancelled]) return;
                    UIImage *image = [self.cache getImageForKey:self.cacheKey withType:YYImageCacheTypeDisk];
                    if (image) {
                        [self.cache setImage:image imageData:nil forKey:self.cacheKey withType:YYImageCacheTypeMemory];
                        [self performSelector:@selector(_didReceiveImageFromDiskCache:) onThread:[self.class _networkThread] withObject:image waitUntilDone:NO];
                    } else {
                        [self performSelector:@selector(_startRequest:) onThread:[self.class _networkThread] withObject:nil waitUntilDone:NO];
                    }
                });
`
我的理解，从磁盘读文件虽然会有些耗时，但不应该能到会被人察觉到图片切换过程的地步，更多的原因会不会是这个地方的异步操作去读图片，拿到之后再返回主线程交给imageView，在异步线程做的操作太多，才会使图片切换的延时更加明显，或者说是不是异步操作就无法避免这种图片切换被察觉的过程，不知道有没有更好的办法

**Comment by ibireme** [comment]
从磁盘读取文件确实很慢，你可以看一下 https://github.com/ibireme/YYCache 这个地方的测试图表，在 iPhone6 64G 上，每次读取 100KB 的数据，每秒钟最多只能完成 300 次左右。屏幕刷新率是 60 次每秒，如果一次读取了超过 4、5 张图片，界面就肯定会卡顿（这还不考虑主线程的其它操作耗时）。

想要界面不卡顿，就不能同步读取磁盘；如果还要视图不闪动，那只能尝试尽早预先加载了，比如提前在后台线程取一次图片，让它从磁盘缓存进入内存缓存。

至于 SDWebImage 的这个方法，你可以看一下这个 Issues：https://github.com/rs/SDWebImage/issues/793 

> this method for using the previously cached image was just added (see #541 and #599) to avoid the flickering between placeholder and the image that is cached (in that case). The author just added it for UIImageView. You are correct, we should rewrite this in an async manner. Are you available for this?

**Comment by zyi1992** [comment]
好的，谢谢你的答复

**Comment by d553296416** [comment]
SDWebImage 有封装出的方法 sd_setImageWithPreviousCachedImageWithURL。yy好像没有但自己写一个逻辑一样的也不难，都有卡顿问题 。。。。。还有就是sdwebimage设置option为SDWebImageDelayPlaceholder好像可以解决，  如果又不想卡又不想闪，afnetworking的图片加载可以满足你

**Comment by dreampiggy** [comment]
@d553296416 其实ibireme说的是对的。因为UIKit（Core Animation）的渲染方式决定了，只有在同一个runloop中进行的多次调用（比如`setImage:`)，才会被忽略中间态。如果要做到Cell Reuse兼容，那么你必须在调用方法开始前，首先触发一个`setImage:`（一般就是placeholder），这时候，假如Memory Cache空了，你有两种选择：

1. 如果决定走同步的取Disk Cache，那么可能会稍稍影响帧率（你可以尝试一下那个`diskCacheReadingOptions`设置成`NSDataReadingMappedIfSafe`来使用mmap，减少IO时间），但是这能够保证Disk Image再次调用`setImage:`的时候，中间placeholder会被忽略而不渲染，因此不会出现任何闪烁。除了那个旧的API，SD会有一个`SDWebImageQueryDiskSync`选项来直接设置
2. 如果决定走异步的取Disk Cache，那么肯定placeholder会被渲染，这时候Disk Cache完成触发了`setImage:`，就会替换新图片，产生一个闪烁。其实之所以是“闪烁”，是因为磁盘速度，比起内存速度要慢得多，但是比网络图要快得多，不然其实理论上网络图这种异步的都应该叫做“闪烁” 😄 

预加载同步磁盘缓存到内存缓存是一个方式，但是这个成本非常高而且不好控制，而且容易导致内存无谓的占用（框架不知道该同步哪些图），因此一般都没人这么做，如果要尝试估计只敢自己业务真的需要这样处理的地方，手动处理一下，同步指定的那些图。

当然，如果只想避免闪烁，还可以暴力一点，直接当前取图禁止走磁盘缓存，只允许内存缓存和网络图，这样也能避免这个问题（SD有一个`SDWebImageCacheMemoryOnly`）。或者可以取巧一点，通过一个动画来减少这种视觉上的“闪烁”，这也是一般采取的方式。
