### ISSUE TITLE
使用YYWebImageOptionHandleCookies选项请求回来的图片模糊

### ISSUE THREAD

**Issue by wrshi** [ibireme/YYWebImage#76]
hello~嗯我调得以下这个方法，请求回来的图片是模糊的，换用SDWebImage以后不会出现模糊的问题，可以排除url设置的问题。可不可以帮忙看一下呐？ 
  
 [self.avatarView yy_setImageWithURL:[NSURL URLWithString:self.item.avatar]
                      placeholder:nil
                          options:YYWebImageOptionHandleCookies
                         progress:nil
                        transform:^UIImage *(UIImage *image, NSURL *url) {
                            image = [image yy_imageByResizeToSize:CGSizeMake(avatarViewWidthHeight, avatarViewWidthHeight) contentMode:UIViewContentModeScaleToFill];
                            return [image yy_imageByRoundCornerRadius:avatarViewWidthHeight / 2];
                        }
                       completion:nil
     ];

**Comment by ibireme** [comment]
SDWebImage 可没有 transform 这个过程啊。。去掉这个看看。

另外，SDWebImage 的 UIImage.scale 是 1，YYWebImage 的是根据设备屏幕决定的。

**Comment by ibireme** [comment]
如果有后续跟进，可以 reopen。
