### ISSUE TITLE
YYWebImage 能否主动清内存？

### ISSUE THREAD

**Issue by acBool** [ibireme/YYWebImage#77]
当gif太多时，使用YYWebImage 仍旧会有内存过高的问题，有没有方法能够主动清内存呢？

**Comment by ibireme** [comment]
收到内存警告时，会自动清除内存的。

如果想控制网络图片内存缓存，可以设置下  [YYWebImageManager sharedManager].cache.memoryCache. costLimit; 。如果想控制播放视图的缓存，可以设置下 animatedImageView. maxBufferSize;
