### ISSUE TITLE
为什么这儿调用两次imageFromData

### ISSUE THREAD

**Issue by Johnkui** [ibireme/YYWebImage#78]
https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYImageCache.m#L139-L140
#140行为什么还要调用一次imageFromData呢，不能直接用newImage吗？

**Comment by ibireme** [comment]
是的，没必要，这块儿浪费了 CPU 资源，应该改一下。。
（好在现有逻辑中没有调用到这块儿）

**Comment by Johnkui** [comment]
谢谢，最近在比较YYWebImage和PINRemoteImage，从实现上和运行的性能上去做比较，后续写点东西总结下，看下来很喜欢你的coding风格和设计能力，不懂的直接来问你了哈！
