### ISSUE TITLE
请问有没有限制并发下载数量的机制？

### ISSUE THREAD

**Issue by speedpursuer** [ibireme/YYWebImage#82]
您好，

是否现有这样的机制：限定一个并发下载数，比如3，则最多同一时间有3个图片下载。第4个请求则在队列中等待前三个中某一个完成了再开始下载。

谢谢！

**Comment by ibireme** [comment]
[YYWebImageManager sharedManager]. queue.maxConcurrentOperationCount

**Comment by speedpursuer** [comment]
感谢帮助！
PS：对iOS不太熟悉，问了这么低级的问题：P
