### ISSUE TITLE
设置图片重连次数的问题

### ISSUE THREAD

**Issue by haofanning** [ibireme/YYWebImage#83]
图片加载失败后会重新发起请求，想问大神一下，这个可以设置重连次数吗？

**Comment by ibireme** [comment]
现在不支持。。

**Comment by haofanning** [comment]
哦，我这设置了一个错误的图片链接，用setImageWithURL:[NSURL URLWithString:imageName] placeholder:caseDefaultImg options:YYWebImageOptionSetImageWithFadeAnimation completion:nil 这个方法后抓包发现这个方法重复发起请求，不知道是我这处理的问题，还是一个bug

**Comment by haofanning** [comment]
不好意思，我自定义了一个轮播图控件，这个问题是由定时器重复调用方法引起的，这个问题关了吧
