### ISSUE TITLE
iphone6上加载大图显示模糊

### ISSUE THREAD

**Issue by zyi1992** [ibireme/YYWebImage#85]
开发中遇到一个问题，同一张图片，在iphone6p上显示是没有问题的但是在iphone6上就会很模糊，后来换成SDWebImage两个机型上都没有问题，不知道有没有人遇到过同样的问题
用的是这个方法做的请求
- (void)loadYYWebImageWithURL:(NSString *)url placeholderImage:(UIImage *)placeholder {
    [self yy_setImageWithURL:[NSURL URLWithString:url] placeholder:placeholder options:YYWebImageOptionSetImageWithFadeAnimation progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        
    } transform:nil completion:^(UIImage * _Nullable image, NSURL * _Nonnull url, YYWebImageFromType from, YYWebImageStage stage, NSError * _Nullable error) {
        
    }];
}

**Comment by ibireme** [comment]
看一下 imageView 的 contentMode。

**Comment by zyi1992** [comment]
UIViewContentModeScaleAspectFill

**Comment by zyi1992** [comment]
感觉问题出在这个地方
                if (allowAnimation) {
                    image = [[YYImage alloc] initWithData:self.data scale:[UIScreen mainScreen].scale];
                    if (shouldDecode) image = [image yy_imageByDecoded];
                    if ([((YYImage *)image) animatedImageFrameCount] > 1) {
                        hasAnimation = YES;
                    }
                } else {
                    YYImageDecoder *decoder = [YYImageDecoder decoderWithData:self.data scale:[UIScreen mainScreen].scale];
                    image = [decoder frameAtIndex:0 decodeForDisplay:shouldDecode].image;
                }
你这里decoderWithData的时候  scale取得是:[UIScreen mainScreen].scale]
 正确的做法是不是应该取图片的scale然后操作  而不是直接拿[UIScreen mainScreen].scale
` UIImage *temp = [UIImage imageWithData:self.data];  
image = [[YYImage alloc] initWithData:self.data scale:temp.scale];`

**Comment by ibireme** [comment]
SDWebImage 是把所有图片的 scale 都设置为 1；另外上面那行代码，创建出的 temp 图片 scale 也是 1，所以在你的场景下，scale=1 应该是没问题的。

我觉得如果用 UIViewContentModeScaleAspectFill 的话，图片应该不至于受到 scale 的影响吧。。

**Comment by zyi1992** [comment]
但是现在的实际情况是 我这里把scale设为1时 图片是没问题的  如果用[UIScreen mainScreen].scale就会很糊  具体原因现在也不是很清楚

**Comment by zyi1992** [comment]
还有 你这里scale 设为[UIScreen mainScreen].scale的理由是什么？

**Comment by ibireme** [comment]
UIImageView contentMode 如果设置为 center/top/left/bottom/right，这样能让图片像素对齐到屏幕。

**Comment by alexlee928** [comment]
大屏幕的情况下,会导致一张清晰的图片,缓存为一一张模糊的图片

@ibireme
