### ISSUE TITLE
能否给YYImageCache增加一个接口，传一个URL，返回缓存文件地址

### ISSUE THREAD

**Issue by dechaos** [ibireme/YYWebImage#86]
我们对webview做了修改，可以执行js脚本替换并加载本地的image文件，因为是js写的，所以需要YYImageCache返回一个已下载图片的缓存filePath，替换到对应的html里加快加载过程。

**Comment by ibireme** [comment]
这个怕是不行。。默认情况下，如果图片小于 20KB，那会直接存到 SQLite 里，并不会对应单一文件。另外，文件操作都是在内部一个单一的线程去执行的，如果把文件路径暴露出去，那可能会破坏了线程安全。

我建议，这个地方返回图片的 base64 编码数据；或者手动改一下内部的 inlineThreshold 为 0，然后直接用 imageCache.diskCache.path 拼上 "data/" 再拼上 URL 的 md5 （但是这样不太好，需要有内部改动）。

**Comment by dechaos** [comment]
明白了，多谢指教
