### ISSUE TITLE
YYWebImage同一个界面显示多张gif图片导致cpu占用过高。

### ISSUE THREAD

**Issue by samhzx** [ibireme/YYWebImage#87]
我在使用YYWebImage的时候在同一个tableview里面一次展示了10多个cell每个cell上面都是gif这样滑动的时候导致cpu占用超过100% 请问一下这个要怎样处理呢？

**Comment by ibireme** [comment]
GIF 的解码都试在后台线程进行的所以这个不用担心。
如果把  GIF 先全部解码，那内存占用会过高甚至会导致 App 崩溃，所以相比来说只能这样了。
