### ISSUE TITLE
关于UIImage所占内存大小

### ISSUE THREAD

**Issue by Tpyphone** [ibireme/YYWebImage#89]
你好，请问下为什么只需要算 高度。
- (NSUInteger)imageCost:(UIImage *)image {
    CGImageRef cgImage = image.CGImage;
    if (!cgImage) return 1;
    CGFloat height = CGImageGetHeight(cgImage);
    size_t bytesPerRow = CGImageGetBytesPerRow(cgImage);
    NSUInteger cost = bytesPerRow * height;
    if (cost == 0) cost = 1;
    return cost;
}

对比AFNetWorking 和 SDWebImage

AFNetWorking 的计算方法：
CGSize imageSize = CGSizeMake(image.size.width * image.scale, image.size.height * image.scale);
        CGFloat bytesPerPixel = 4.0;
        CGFloat bytesPerSize = imageSize.width * imageSize.height;
        self.totalBytes = (UInt64)bytesPerPixel * (UInt64)bytesPerSize;

而SDWebImage计算方法：
判断是否为png，再通过系统提供的两个接口转为NSData。

**Comment by ibireme** [comment]
AFNetWorking 假定图片已经解压到内存 Bitmap，并且每像素是 4 Byte（比如 ARGB8888）。这种计算会忽略掉图片用于内存对齐的多余的字节，但误差不大。

YYWebImage 这块儿，也是假定图片已经解压到内存 Bitmap，但具体每像素的字节数、内存对齐用的字节数，都是直接调用 CGImage 接口获取到的，这样比较准确。你可以查看一下 `CGImageGetBytesPerRow` 这个函数的说明文档。

SDWebImage 计算的是图片序列化（编码）后的文件体积，这与图片的宽高就没关系了。

**Comment by Tpyphone** [comment]
非常感谢🙏

**Comment by Norcy** [comment]
实测有些图片并非如此。

比如 https://s3.ax1x.com/2021/02/19/yhsmiF.png

第一个方法，大概 1882384/1024/1024 = 1.79 M

```objc
CGFloat height = CGImageGetHeight(image.CGImage);
size_t bytesPerRow = CGImageGetBytesPerRow(image.CGImage);
CGFloat memory = bytesPerRow * height; // output 1882384
```

第二个方法，大概 7529536/1024/1024 = 7.18 M

```objc
CGSize imageSize = CGSizeMake(image.size.width * image.scale, image.size.height * image.scale);
CGFloat bytesPerPixel = 4.0;
CGFloat bytesPerSize = imageSize.width * imageSize.height;
CGFloat memory = (UInt64)bytesPerPixel * (UInt64)bytesPerSize;  // output 7529536
```

实测下来，Xcode 的内存涨幅大约在 7M 左右，方法 2 更加准确

![image](https://user-images.githubusercontent.com/8423011/108502094-3829a100-72ed-11eb-9f5c-c6deeb280d0f.png)

![image](https://user-images.githubusercontent.com/8423011/108502043-2647fe00-72ed-11eb-85f5-35df7229d26c.png)

测试环境：iPhone11 Pro；Xcode 12.2；使用 Xcode 自带的内存面板查看

测试代码：

```objc
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    
    UIImage *image = [UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL URLWithString:@"https://s3.ax1x.com/2021/02/19/yhsmiF.png"]]];
    UIImageView *imgView = [[UIImageView alloc] initWithImage:image];
    [self.view addSubview:imgView];
    
    CGFloat height = CGImageGetHeight(image.CGImage);
    size_t bytesPerRow = CGImageGetBytesPerRow(image.CGImage);
    CGFloat memory = bytesPerRow * height;
    
    CGSize imageSize = CGSizeMake(image.size.width * image.scale, image.size.height * image.scale);
    CGFloat bytesPerPixel = 4.0;
    CGFloat bytesPerSize = imageSize.width * imageSize.height;
    CGFloat memory2 = (UInt64)bytesPerPixel * (UInt64)bytesPerSize;
});
```
