### ISSUE TITLE
如何判断一张(url)图片是否缓存完成

### ISSUE THREAD

**Issue by lkqin** [ibireme/YYWebImage#9]
如何判断一张图片是否缓存完成?

**Comment by ibireme** [comment]
YYImageCache *cache = [YYWebImageManager sharedManager].cache;
    NSString *key = [[YYWebImageManager sharedManager] cacheKeyForURL:url];
    
    BOOL cached = [cache containsImageForKey:key];
    BOOL cachedInMemory = [cache containsImageForKey:key withType:YYImageCacheTypeMemory];
    BOOL cachedInDisk = [cache containsImageForKey:key withType:YYImageCacheTypeDisk];

**Comment by lkqin** [comment]
thanks very much
