### ISSUE TITLE
有些图片下载不了，在浏览器打开图片地址是可以的，options的渐进式加载模糊效果没有出现

### ISSUE THREAD

**Issue by shiyuan17** [ibireme/YYWebImage#90]
代码和图片地址如下
[testImg yy_setImageWithURL:[NSURL URLWithString:@"http://p1.qqhot.com/G1/M00/A9/61/rBACE1IYT9rzf66kAABuqQjQCTM744.jpg"] options:YYWebImageOptionProgressiveBlur | YYWebImageOptionSetImageWithFadeAnimation];

**Comment by ibireme** [comment]
这个图片在我的浏览器里打开是 404 。。。
另外，渐进式加载需要图片在编码时本身选择了"渐进式"选项。

**Comment by lazycoder417** [comment]
你好  我现在也有个需求是模糊渐进式下载  我也是按上面这个人写的代码
`[self.rightImageView`` yy_setImageWithURL:[NSURL URLWithString:self.feed.rightImageUrl] options:YYWebImageOptionProgressiveBlur | YYWebImageOptionSetImageWithFadeAnimation urlTag:self.feed.rightImageUrl];

可是并不能出现模糊渐进式  请问这个所谓的编码时本身选择渐进式选项是什么意思  万分感谢

**Comment by lazycoder417** [comment]
@shiyuan17    请问  你原来遇到的那个问题  图片下载渐进式的有没有解决掉  我也很想知道如何处理
