### ISSUE TITLE
Resize animated GIF images.

### ISSUE THREAD

**Issue by storix** [ibireme/YYWebImage#92]
Could you tell me, please, is it possible to resize the animated GIF images during the loading process? The documentation states that we can use `transform` block in the following method:

```
[imageView yy_setImageWithURL:url
    placeholder:nil
    options:YYWebImageOptionSetImageWithFadeAnimation
    progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        progress = (float)receivedSize / expectedSize;
    }
    transform:^UIImage *(UIImage *image, NSURL *url) {
        image = [image yy_imageByResizeToSize:CGSizeMake(100, 100) contentMode:UIViewContentModeCenter];
        return [image yy_imageByRoundCornerRadius:10];
    }
    completion:^(UIImage *image, NSURL *url, YYWebImageFromType from, YYWebImageStage stage, NSError *error) {
        if (from == YYWebImageFromDiskCache) {
            NSLog(@"load from disk cache");
        }
    }];
```
But, as far as I can see, it can be used only for still `UIImage` (like png or jpeg). Nevertheless, I tried to apply `yy_imageByResizeToSize` to the image in the`transform` block and, obviously, the animated GIF is being converted to a static image. Maybe I've missed something and there are other methods for this purpose?

**Comment by ibireme** [comment]
`yy_imageByResizeToSize` can only process still image.

Resize GIF image is a very expensive operation: it should decode each frame into memory, resize and then packaged together. You can try the code below, but this may cost lots of CPU and memory:

    UIImage *image;
    if ([image isKindOfClass:[YYImage class]] && ((YYImage *)image).animatedImageFrameCount > 1) {
        YYImage *aniImage = (YYImage *)image;
        YYImageEncoder *encoder = [[YYImageEncoder alloc] initWithType:YYImageTypeGIF];
        encoder.loopCount = aniImage.animatedImageLoopCount;
        for (NSUInteger i = 0; i < aniImage.animatedImageFrameCount; i++) {
            @autoreleasepool {
                UIImage *image = [aniImage animatedImageFrameAtIndex:i];
                image = [image yy_imageByResizeToSize:CGSizeMake(100, **100)];**
                [encoder addImage:image duration:[aniImage animatedImageDurationAtIndex:i]];
            }
        }
        NSData *data = [encoder encode];
        image = [YYImage imageWithData:data scale:image.scale];
    }

**Comment by storix** [comment]
Thank you for a quick response!

In my App I'm trying to populate the collection view with the animated GIF images. Just thought that I can improve scrolling performance by caching GIFs with the reduced size. Since GIF resizing is such an expensive operation, how do you think, is it OK to just set the collection view cell's `imageView` using the following method:

```
[cell.imageView yy_setImageWithURL:url
    options:YYWebImageOptionSetImageWithFadeAnimation];
```

**Comment by ibireme** [comment]
If you use `YYAnimatedImageView` to display animated image, you may set `imageView.runloopMode` with `NSDefaultRunLoopMode` to pause the animation during UIScrollView scrolling.

**Comment by storix** [comment]
Ok, I got it. Thanks again. I'm closing the issue.
