### ISSUE TITLE
手动清除缓存之后磁盘缓存失效

### ISSUE THREAD

**Issue by zyi1992** [ibireme/YYWebImage#94]
调用之后 
[[YYImageCache sharedCache].diskCache removeAllObjects];
 [[YYImageCache sharedCache].memoryCache removeAllObjects];
磁盘缓存不能用了
错误信息有三类
Unknown error calling sqlite3_step (8: attempt to write a readonly database) eu
 DB Query: INSERT INTO statistics_records (uniqueID, type, time,aid, duration, pageID,eventID, extendPara) VALUES (?, ?, ? ,? ,? ,? ,? ,?)
[YYKVStorage _dbOpen] line:114 sqlite open failed (14).

**Comment by ibireme** [comment]
请更新 pod 确保 YYCache 版本在 1.0.3 以上：
https://github.com/ibireme/YYCache/releases

**Comment by zyi1992** [comment]
找到原因了  我前面在清除app缓存的时候把com.ibireme.yykit文件夹下的内容也清空了  之后在调用_dbOpen的时候  由于manifest.sqlite已经不存在了  所以会打开失败   ps:建议这里可以加一个判空处理 如果存在打开manifest.sqlite不存在再重新创建一次  不过一般不会出现我这种情况 可以忽略
