### ISSUE TITLE
图片资源在外国服务器,有时候Url响应比较慢 

### ISSUE THREAD

**Issue by Sdoy** [ibireme/YYWebImage#95]
1.图片资源在外国服务器,有时候Url响应比较慢 没有发现有Retry类似的YYWebImageOptions?有什么变通的方法吗?
2.怎么下载gif的第一帧用来做展示?因为点击大图后才开始播放gif

**Comment by ibireme** [comment]
响应慢这个没办法，只能设置下 ImageManager 的 timeout 了，但这仍然解决不了慢的问题。

目前没有提供 Retry 的方法。如果提供的话，可能需要很多可配置的策略，比如重试几次，404 是否还要再重试，等等，有些麻烦。

至于 GIF 的话，如果能确定一个 URL 后面是 GIF，那可以用 YYWebImageOptionProgressive 这个参数，来边下载边显示。如果需要更好的策略，可能需要修改一些内部代码了。。
