### ISSUE TITLE
微博正文、评论中的图片链接 decode fail 

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYWebImage#96]
**场景：** 
微博正文、评论中均为短链，通过开放平台的转链 API 转换成形如 `http://photo.weibo.com/h5/repost/reppic_id/1022:230796d393e89a2f6d74cfaec1fcd0b3372d43?url_type=39&object_type=collection&pos=1` 的长链。

但是这种链接很奇怪。
* 首先没有后缀，用 YYWebImage 无法解码；
* 其次用浏览器却可以打开，右键复制图片地址也能得到正常的地址：`http://ww4.sinaimg.cn/bmiddle/62b4e495gw1evvzalu8y8j20p018ggnw.jpg` 。

YYKitDemo 中是直接在 api dump 里面保留了正常的地址，所以没有这个问题。故请教 YYWebImage 如何解析类似上面 `http://photo.weibo.com/h5/repost/reppic_id/1022:230796d393e89a2f6d74cfaec1fcd0b3372d43?url_type=39&object_type=collection&pos=1` 这样的图片？

谢谢！

**Comment by ibireme** [comment]
图片的解码不是根据扩展名来的，而是根据文件头的 magic number 之类的东西来的。

这里打不开，是因为这个链接需要有登录信息才能访问。这个也可以打印一下回调中的 error 信息看看。

**Comment by KittenYang** [comment]
回调是这样的：
`url`:
http://photo.weibo.com/h5/comment/compic_id/1022:23059768573cd0c5db5fed9a2b14a06216a4db

`imageFromType`:
YYWebImageFromType

`imageStage`:
YYWebImageStage

`error`:
Error Domain=com.ibireme.image Code=-1 "Web image decode fail." UserInfo={NSLocalizedDescription=Web image decode fail.}

**Comment by ibireme** [comment]
下载到的数据应该是 HTML 文本，所以解码失败了。

**Comment by KittenYang** [comment]
是的。加了 accesstoken 参数也不行。目前想不到解决办法。
