### ISSUE TITLE
autoPlayAnimatedImage 设置无效？

### ISSUE THREAD

**Issue by lionner** [ibireme/YYWebImage#97]
autoPlayAnimatedImage 设置了为NO了，但是，UI上显示的还是在动
好多个 YYAnimatedImageView的情况下，只根据一个变量来全部更改 autoPlayAnimatedImage

**Comment by ibireme** [comment]
每一个 YYAnimatedImageView 实例都有自己的 autoPlayAnimatedImage 属性，这并不是一个全局变量。

这个值只控制`当视图发生变化时是否自动播放`，如果图片已经播放了或者停止着，则这个值不会起作用。这是应该调用 startAnimating 和 stopAnimating 来控制动画。

**Comment by lionner** [comment]
ok，谢谢！
