### ISSUE TITLE
使用uicollectionView同时加载多张图片时会出现一些cell的图片显示不出来的情况

### ISSUE THREAD

**Issue by drpang** [ibireme/YYWebImage#98]

**Comment by ibireme** [comment]
描述太简单。

**Comment by drpang** [comment]
[self.showImgView sd_setImageWithURL:[NSURL URLWithString:urlStr] placeholderImage:[UIImage imageNamed:@"loading.png"] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            if (error) {
                self.showImgView.image = [UIImage imageNamed:@"loadError.png"];
                NSLog(@"the image load fail! %@" , error);
            }
        }];

log: the image load fail! Error Domain=NSURLErrorDomain Code=403 "(null)
如果失败一次，再次layoutSubviews还是返回error失败，
Sdwebimage相关问题：https://github.com/rs/SDWebImage/issues/1228

**Comment by drpang** [comment]
同样的问题：错误信息Error Domain=NSURLErrorDomain Code=400 "(null)同样失败一次，再次layoutSubviews还是返回error失败，

**Comment by ibireme** [comment]
访问图片时，服务器返回了 403 错误码。应该问下服务端是否出错、是否需要额外认证。

如果像 SD 那个问题那样需要 User-Agent，这里也可以设置 [YYWebImageManager sharedManager].headers 或者 headersFilter 来进行额外处理。

**Comment by drpang** [comment]
ok我试一下，不过我换成sdwebimage没有这个问题，如果验证ok的的话是否客户端改更好

**Comment by drpang** [comment]
设置后还是有问题，依然返回403，但是我换用Sdwebimage时没任何问题，不清楚问题出在哪里

**Comment by ibireme** [comment]
403 Forbidden 是服务端返回的错误码，这个应该询问服务端错误原因，或者抓包看看请求的差异。
