### ISSUE TITLE
YYAnimatedImageView使用时，如果替换图片路径会有闪动。

### ISSUE THREAD

**Issue by cvby** [ibireme/YYWebImage#99]
_imageView = [YYAnimatedImageView new];
NSURL *path = [[NSBundle mainBundle]URLForResource:@"guidegif" withExtension:@"gif"];
    _imageView.yy_imageURL = path;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3.65 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSURL *path2 = [[NSBundle mainBundle]URLForResource:@"guidegif_loop" withExtension:@"gif"];
        _imageView.yy_imageURL = path2;
});
在第二次赋值新的url的时候，imageView会空白一下，然后再显示出来。

**Comment by ibireme** [comment]
当设置新的 url 时，会把旧的 URL 和图片清除，但这时新 URL 内容还未请求完成，就会有闪动。

这里可以传入 placeholder 来作为替代，或者用 YYWebImageOptionAvoidSetImage 来手动设置图片。

**Comment by cvby** [comment]
现在我在替换的时候创建一个yyimage去加载gif，然后让imageView去加载yyimage，就可以解决这个问题。因为这里我需要连续的动画效果，传入placeholder不是太好，谢谢你的解答。
